# Data Preprocessing notebook
* We will use this notebook to preprocess the data we are going to use in our optimization problem.

## Importing packages needed

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Reading our database

In [2]:
df = pd.read_csv("test_data/students.csv")
df.head()

,Assessor,Aluno,tempo,Idade,Gênero,Quão compatível com seu assessor você se considera?,Onde fez/faz ensino médio?,Alguma religião?,Gosta de esportes?,Como foi/está sendo a qualidade de seu ensino médio?,...,Quão sensível você é?,Você gosta de ser cobrado?,Você é competitivo?,Você é aberto a mudanças? ou é mais resistente?,Você gosta de fazer simulado?,Você recebe apoio da sua família?,Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?,Quão motivado você está?,Qual é seu maior problema?,Você prefere um assessor do mesmo sexo?
0,Ariel,Adriel Ribeiro,3,18.0,Masculino,8.0,Motiva,Cristianismo,Sim,5.0,...,3.0,Não,Talvez,Aberto,Sim,Sim,Os dois,8.0,Procrastinação,"sim, fico mais confortável"
1,Ariel,Alyce Dantas,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ariel,Barbara Camargo,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ariel,Breno Alves Amorim,2,19.0,Masculino,10.0,Outro em João Pessoa,Cristianismo,Sim,3.0,...,7.0,Sim,Sim,Aberto,Sim,mais ou menos,Os dois,10.0,Procrastinação,Indiferente
4,Ariel,Caio Paiva,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

* We can see that the data is ok.

In [3]:
df.shape #we have 209 examples with 36 columns each

(219, 36)

In [4]:
df.describe()

,tempo,Idade,Quão compatível com seu assessor você se considera?,Como foi/está sendo a qualidade de seu ensino médio?,Quantas vezes já fez enem? (sem contar como treineiro),Quão sensível você é?,Quão motivado você está?
count,219.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000
mean,4.105023,18.210191,9.165605,3.694268,1.541401,7.159236,7.089172
std,1.032909,1.908254,1.042969,0.938236,1.411902,1.926567,1.614739
min,1.000000,15.000000,5.000000,0.000000,0.000000,2.000000,3.000000
25%,4.000000,17.000000,9.000000,3.000000,0.000000,6.000000,6.000000
50%,4.000000,18.000000,9.000000,4.000000,1.000000,7.000000,7.000000
75%,5.000000,19.000000,10.000000,4.000000,2.000000,9.000000,8.000000
max,5.000000,24.000000,10.000000,5.000000,6.000000,10.000000,10.000000

* The variable *tempo* (**time**) is in a scale such as these are the corresponding(in minutes):
<table border = "1">

    <tr>
        <td>Till 5</td>
        <td>between 5 e 10</td>
        <td>between 10 e 15</td>
        <td>between 15 e 20</td>
        <td>between 20 e 25</td>
        <td>25+</td>
    </tr>
    
    <tr>
        <td>0</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
    </tr>
</table>

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 36 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   Assessor                                                                          219 non-null    object
 1   Aluno                                                                             219 non-null    object
 2   tempo                                                                             219 non-null    int64
 3   Idade                                                                             157 non-null    float64
 4   Gênero                                                                            157 non-null    object
 5   Quão compatível com seu assessor você se considera?                               157 non-null    float64
 6   Onde fez/faz ensino médio?                                                        157 non-null    object
 7   Alguma religião?                                                                  157 non-null    object
 8   Gosta de esportes?                                                                157 non-null    object
 9   Como foi/está sendo a qualidade de seu ensino médio?                              157 non-null    float64
 10  Você se envolve com política?                                                     157 non-null    object
 11  Como se considera politicamente?                                                  155 non-null    object
 12  Que área compreende o curso que deseja fazer na faculdade?                        157 non-null    object
 13  Qual sua área preferida no ENEM?                                                  157 non-null    object
 14  Quantos irmãos você tem?                                                          157 non-null    object
 15  Tem ou já teve algum problema de saúde físico?                                    157 non-null    object
 16  Tem ou já teve algum problema de saúde mental?                                    157 non-null    object
 17  Pretende fazer faculdade na paraíba?                                              157 non-null    object
 18  Pratica atividade física com frequência?                                          157 non-null    object
 19  Introvertido ou extrovertido?                                                     157 non-null    object
 20  No tempo livre prefere:                                                           156 non-null    object
 21  Tem facilidade em fazer amizades?                                                 157 non-null    object
 22  Que tipo de assessor prefere? mais técnico ou que lide melhor com seu emocional?  157 non-null    object
 23  Quantas vezes já fez enem? (sem contar como treineiro)                            157 non-null    float64
 24  Você se considera uma pessoa paciente?                                            157 non-null    object
 25  Você é organizado?                                                                157 non-null    object
 26  Quão sensível você é?                                                             157 non-null    float64
 27  Você gosta de ser cobrado?                                                        157 non-null    object
 28  Você é competitivo?                                                               157 non-null    object
 29  Você é aberto a mudanças? ou é mais resistente?                                   157 non-null    object
 30  Você gosta de fazer simulado?                                                     157 non-null    object
 31  Você recebe apoio da sua família?                                                 157 non-null    object
 32  Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?         157 non-null    object
 33  Quão motivado você está?                                                          157 non-null    float64
 34  Qual é seu maior problema?                                                        156 non-null    object
 35  Você prefere um assessor do mesmo sexo?                                           157 non-null    object
dtypes: float64(6), int64(1), object(29)
memory usage: 61.7+ KB

* Althought there are 219 rows with different students data, we have some missing data as we can see bellow:

In [6]:
df.isnull().sum()/df.shape[0] * 100

Assessor                                                                             0.000000
Aluno                                                                                0.000000
tempo                                                                                0.000000
Idade                                                                               28.310502
Gênero                                                                              28.310502
Quão compatível com seu assessor você se considera?                                 28.310502
Onde fez/faz ensino médio?                                                          28.310502
Alguma religião?                                                                    28.310502
Gosta de esportes?                                                                  28.310502
Como foi/está sendo a qualidade de seu ensino médio?                                28.310502
Você se envolve com política?                                                       28.310502
Como se considera politicamente?                                                    29.223744
Que área compreende o curso que deseja fazer na faculdade?                          28.310502
Qual sua área preferida no ENEM?                                                    28.310502
Quantos irmãos você tem?                                                            28.310502
Tem ou já teve algum problema de saúde físico?                                      28.310502
Tem ou já teve algum problema de saúde mental?                                      28.310502
Pretende fazer faculdade na paraíba?                                                28.310502
Pratica atividade física com frequência?                                            28.310502
Introvertido ou extrovertido?                                                       28.310502
No tempo livre prefere:                                                             28.767123
Tem facilidade em fazer amizades?                                                   28.310502
Que tipo de assessor prefere? mais técnico ou que lide melhor com seu emocional?    28.310502
Quantas vezes já fez enem? (sem contar como treineiro)                              28.310502
Você se considera uma pessoa paciente?                                              28.310502
Você é organizado?                                                                  28.310502
Quão sensível você é?                                                               28.310502
Você gosta de ser cobrado?                                                          28.310502
Você é competitivo?                                                                 28.310502
Você é aberto a mudanças? ou é mais resistente?                                     28.310502
Você gosta de fazer simulado?                                                       28.310502
Você recebe apoio da sua família?                                                   28.310502
Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?           28.310502
Quão motivado você está?                                                            28.310502
Qual é seu maior problema?                                                          28.767123
Você prefere um assessor do mesmo sexo?                                             28.310502
dtype: float64

* In almost every variable besides time, name and assessor we have 28% of missing data. It does influence in the result but we will solve this by two different means.

## Distributions

In [7]:
#overall compatibility
df["Quão compatível com seu assessor você se considera?"].describe()

count    157.000000
mean       9.165605
std        1.042969
min        5.000000
25%        9.000000
50%        9.000000
75%       10.000000
max       10.000000
Name: Quão compatível com seu assessor você se considera?, dtype: float64

In [8]:
compatibility = {}
for assessor in df["Assessor"].unique():
    mean = df[df["Assessor"] == assessor]["Quão compatível com seu assessor você se considera?"].mean()
    compatibility[assessor] = mean;

In [9]:
# mean compatibility
pd.DataFrame(compatibility.values(),index=compatibility.keys()).sort_values(by=0).describe()

               0
count  15.000000
mean    9.166296
std     0.478565
min     8.285714
25%     8.925000
50%     9.000000
75%     9.577778
max     9.833333

In [10]:
df.tempo.describe()

count    219.000000
mean       4.105023
std        1.032909
min        1.000000
25%        4.000000
50%        4.000000
75%        5.000000
max        5.000000
Name: tempo, dtype: float64

* We are aiming to maximize the overall compatibility while minimizing the work the employees have

## Reading the assessors data

In [11]:
df_assessores = pd.read_csv("test_data/assessores.csv").drop(15)
df_assessores

,Quem é você?,Idade,Gênero,Onde fez ensino médio?,Alguma religião?,Gosta de esportes?,Como foi a qualidade de seu ensino médio?,Você se envolve com política?,Como se considera politicamente?,Que área compreende o curso que deseja fazer/faz na faculdade?,...,Quão sensível você é?,Você costuma cobrar seus alunos?,Você é competitivo?,Você é aberto a mudanças? ou é mais resistente?,Você costuma passar simulados pros alunos?,Você recebe apoio da sua família?,você costuma conversar com seus alunos sobre a vida pessoal deles ou só estudos?,Quão bom você é em motivar seus alunos?,Qual problema você é mais apto a ajudar os seus alunos a resolver?,Você tem problemas em receber alunos de sexo diferente?
0,Davi,20,Masculino,Motiva,Cristianismo,Sim,5,"Não, prefiro focar em outras coisas.",Centro,Saúde,...,5,Sim,Talvez,Aberto,Sim,Sim,Os dois,8,Procrastinação,Não
1,Lorenna,20,Feminino,Motiva,Agnóstico,Sim,4,"Não, prefiro focar em outras coisas.",Esquerda,Saúde,...,7,Sim,Sim,Aberto,Sim,mais ou menos,Os dois,9,Procrastinação,Não
2,Rayssa,23,Feminino,Motiva,Cristianismo,Não,5,"Não, prefiro focar em outras coisas.",Direita,Saúde,...,6,Sim,Sim,Aberto,Sim,Sim,Os dois,5,Dedicação,Não
3,Débora,20,Feminino,Outro em João Pessoa,Cristianismo,Sim,3,"Sim, acho importante.",Esquerda,Saúde,...,4,Sim,Sim,Aberto,Sim,Sim,Os dois,7,Dedicação,Não
4,Glaucielle,24,Feminino,Outro em João Pessoa,Cristianismo,Sim,3,"Sim, acho importante.",Esquerda,Saúde,...,8,Sim,Talvez,Aberto,Sim,Sim,Os dois,9,Procrastinação,Não
5,Patriota,22,Masculino,Motiva,Cristianismo,Sim,3,"Sim, acho importante.",Esquerda,Saúde,...,8,Talvez,Sim,Aberto,Sim,Sim,Os dois,8,Dedicação,Não
6,Ariel,21,Masculino,Motiva,Ateísmo,Sim,4,"Sim, acho importante.",Esquerda,Saúde,...,7,Sim,Sim,Aberto,Sim,Sim,Os dois,10,Concentração,Não
7,Rodrigo,19,Masculino,Outra fora de João Pessoa,Cristianismo,Sim,4,"Não, prefiro focar em outras coisas.",Apolítico,Saúde,...,9,Talvez,Não,Aberto,Sim,Não,Os dois,7,Concentração,Não
8,Carolzinha,24,Feminino,Outra fora de João Pessoa,Cristianismo,Sim,4,"Sim, acho importante.",Esquerda,Saúde,...,8,Sim,Não,Aberto,Sim,Sim,Os dois,9,Dedicação,Não
9,Eduardo,24,Masculino,Motiva,Cristianismo,Sim,4,"Sim, acho importante.",Esquerda,Saúde,...,7,Talvez,Talvez,Aberto,Sim,Sim,Os dois,9,Ansiedade,Não
10,Mateus Tavares,19,Masculino,Motiva,Cristianismo,Sim,4,"Não, prefiro focar em outras coisas.",Centro,Saúde,...,8,Talvez,Sim,Aberto,Sim,Sim,Os dois,8,Concentração,Não
11,Fabiana,22,Feminino,Outro em João Pessoa,Cristianismo,Não,3,"Sim, acho importante.",Direita,Saúde,...,8,Talvez,Talvez,Aberto,Sim,Sim,Os dois,9,Dedicação,Não
12,Catharina,20,Feminino,Geo,Cristianismo,Não,3,"Não, prefiro focar em outras coisas.",Direita,Saúde,...,8,Sim,Não,Aberto,Sim,Sim,Os dois,9,Sentimento de incapacidade,Não
13,Itamar,20,Masculino,Motiva,Cristianismo,Sim,3,"Não, prefiro focar em outras coisas.",Centro,Exatas,...,3,Sim,Sim,Aberto,Sim,Sim,Os dois,9,Procrastinação,Não
14,Gelielison,21,Masculino,Outra fora de João Pessoa,Cristianismo,Sim,3,"Sim, acho importante.",Esquerda,Saúde,...,8,Sim,Sim,Aberto,Sim,Sim,Os dois,8,Procrastinação,Não

## Removing missing values

In [12]:
df_students_answered = df[~df.Idade.isna()]

In [13]:
df_students_notAnswered = df[df.Idade.isna()]

In [14]:
df_students_answered.isnull().sum()

Assessor                                                                            0
Aluno                                                                               0
tempo                                                                               0
Idade                                                                               0
Gênero                                                                              0
Quão compatível com seu assessor você se considera?                                 0
Onde fez/faz ensino médio?                                                          0
Alguma religião?                                                                    0
Gosta de esportes?                                                                  0
Como foi/está sendo a qualidade de seu ensino médio?                                0
Você se envolve com política?                                                       0
Como se considera politicamente?                                                    2
Que área compreende o curso que deseja fazer na faculdade?                          0
Qual sua área preferida no ENEM?                                                    0
Quantos irmãos você tem?                                                            0
Tem ou já teve algum problema de saúde físico?                                      0
Tem ou já teve algum problema de saúde mental?                                      0
Pretende fazer faculdade na paraíba?                                                0
Pratica atividade física com frequência?                                            0
Introvertido ou extrovertido?                                                       0
No tempo livre prefere:                                                             1
Tem facilidade em fazer amizades?                                                   0
Que tipo de assessor prefere? mais técnico ou que lide melhor com seu emocional?    0
Quantas vezes já fez enem? (sem contar como treineiro)                              0
Você se considera uma pessoa paciente?                                              0
Você é organizado?                                                                  0
Quão sensível você é?                                                               0
Você gosta de ser cobrado?                                                          0
Você é competitivo?                                                                 0
Você é aberto a mudanças? ou é mais resistente?                                     0
Você gosta de fazer simulado?                                                       0
Você recebe apoio da sua família?                                                   0
Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?           0
Quão motivado você está?                                                            0
Qual é seu maior problema?                                                          1
Você prefere um assessor do mesmo sexo?                                             0
dtype: int64

* showing all the ones that still have missing data

In [15]:
df_students_answered.loc[df_students_answered["Qual é seu maior problema?"].isnull()]

,Assessor,Aluno,tempo,Idade,Gênero,Quão compatível com seu assessor você se considera?,Onde fez/faz ensino médio?,Alguma religião?,Gosta de esportes?,Como foi/está sendo a qualidade de seu ensino médio?,...,Quão sensível você é?,Você gosta de ser cobrado?,Você é competitivo?,Você é aberto a mudanças? ou é mais resistente?,Você gosta de fazer simulado?,Você recebe apoio da sua família?,Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?,Quão motivado você está?,Qual é seu maior problema?,Você prefere um assessor do mesmo sexo?
110,Gelielison,Isadora Ferraz,5,17.0,Feminino,10.0,Outra fora de João Pessoa,Cristianismo,Sim,4.0,...,8.0,Sim,Sim,Resistente,Não,Sim,Os dois,7.0,NaN,Indiferente

* Here and in all subsequent cases we will replace the nans with the mode of the column or with a variable that wont result in any restriction in the end

In [16]:
df_students_answered["Qual é seu maior problema?"].value_counts()

Procrastinação                                                                                            67
Concentração                                                                                              48
Velocidade                                                                                                18
Dedicação                                                                                                  5
Na quarentena to precisando lidar com responsabilidades (mudança de apto, procura de móveis, reforma)      1
Falta força de vontade também                                                                              1
no momento é o barulho em casa, fora isso eu acho que é a ansiedade.                                       1
Autoconfiança                                                                                              1
Ansiedade e falta de confiança/ segurança no que eu faço!                                                  1
Velocidade e procrastinação                                                                                1
Procrastinação e Concentração                                                                              1
Resolver questões e fzr simulado                                                                           1
Estresse                                                                                                   1
Organização                                                                                                1
Concentração, procrastinação e velocidade                                                                  1
Autoconfiança                                                                                              1
Não perder o foco                                                                                          1
Eficiencia                                                                                                 1
Alguns problemas pessoais tem afetado.                                                                     1
Resiliência                                                                                                1
Emocional                                                                                                  1
Falta de interesse em algumas áreas                                                                        1
Name: Qual é seu maior problema?, dtype: int64

In [17]:
df_students_answered["Qual é seu maior problema?"][110] = "Procrastinação"

/home/itamar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/itamar/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3319: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [18]:
df_students_answered.loc[df_students_answered["No tempo livre prefere:"].isnull()]

,Assessor,Aluno,tempo,Idade,Gênero,Quão compatível com seu assessor você se considera?,Onde fez/faz ensino médio?,Alguma religião?,Gosta de esportes?,Como foi/está sendo a qualidade de seu ensino médio?,...,Quão sensível você é?,Você gosta de ser cobrado?,Você é competitivo?,Você é aberto a mudanças? ou é mais resistente?,Você gosta de fazer simulado?,Você recebe apoio da sua família?,Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?,Quão motivado você está?,Qual é seu maior problema?,Você prefere um assessor do mesmo sexo?
107,Gelielison,Eduardo Paulo Queiroz Torres,4,16.0,Masculino,8.0,Motiva,Cristianismo,Sim,4.0,...,5.0,Sim,Sim,Aberto,Sim,Sim,Os dois,8.0,Procrastinação,"sim, fico mais confortável"

In [19]:
df_students_answered["No tempo livre prefere:"].value_counts()

comer ou cinema                 58
ficar em casa/assistir série    45
balada                          41
esporte                         12
Name: No tempo livre prefere:, dtype: int64

In [20]:
df_students_answered["No tempo livre prefere:"][107] = "comer ou cinema"

/home/itamar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/itamar/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3319: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [21]:
df_students_answered.loc[df_students_answered["Como se considera politicamente?"].isnull()]

,Assessor,Aluno,tempo,Idade,Gênero,Quão compatível com seu assessor você se considera?,Onde fez/faz ensino médio?,Alguma religião?,Gosta de esportes?,Como foi/está sendo a qualidade de seu ensino médio?,...,Quão sensível você é?,Você gosta de ser cobrado?,Você é competitivo?,Você é aberto a mudanças? ou é mais resistente?,Você gosta de fazer simulado?,Você recebe apoio da sua família?,Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?,Quão motivado você está?,Qual é seu maior problema?,Você prefere um assessor do mesmo sexo?
104,Gelielison,Adrya Catharinne Santos Sousa da Silva,5,17.0,Feminino,9.0,Outro em João Pessoa,Cristianismo,Não,4.0,...,10.0,Sim,Sim,Aberto,Sim,Sim,Os dois,8.0,Procrastinação,Indiferente
137,Itamar,Gabriel Bandeira,3,19.0,Masculino,8.0,Outra fora de João Pessoa,Cristianismo,Não,4.0,...,8.0,Não,Sim,Aberto,Sim,mais ou menos,Os dois,7.0,"no momento é o barulho em casa, fora isso eu a...",Indiferente

In [22]:
df_students_answered["Como se considera politicamente?"].value_counts()

Centro       53
Direita      46
Apolítico    29
Esquerda     27
Name: Como se considera politicamente?, dtype: int64

In [23]:
df_students_answered["Como se considera politicamente?"][[104,137]] = "Centro"

/home/itamar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/itamar/anaconda3/lib/python3.7/site-packages/pandas/core/series.py:1092: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_labels(key, value)
/home/itamar/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3319: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

## Creating the compatibility matrix

* This matrix is a result of the compatibility between Students and assessores. This will be the heaviest part of this application case.

In [24]:
# creating a matrix with all 0
compatibility_matrix = pd.DataFrame(0, columns = df.Assessor.unique(), index = df_students_answered.Aluno)

## Creating the compatibility metric

In [25]:
df_students_answered.head(1)

,Assessor,Aluno,tempo,Idade,Gênero,Quão compatível com seu assessor você se considera?,Onde fez/faz ensino médio?,Alguma religião?,Gosta de esportes?,Como foi/está sendo a qualidade de seu ensino médio?,...,Quão sensível você é?,Você gosta de ser cobrado?,Você é competitivo?,Você é aberto a mudanças? ou é mais resistente?,Você gosta de fazer simulado?,Você recebe apoio da sua família?,Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?,Quão motivado você está?,Qual é seu maior problema?,Você prefere um assessor do mesmo sexo?
0,Ariel,Adriel Ribeiro,3,18.0,Masculino,8.0,Motiva,Cristianismo,Sim,5.0,...,3.0,Não,Talvez,Aberto,Sim,Sim,Os dois,8.0,Procrastinação,"sim, fico mais confortável"

In [26]:
df_assessores.head(1)

,Quem é você?,Idade,Gênero,Onde fez ensino médio?,Alguma religião?,Gosta de esportes?,Como foi a qualidade de seu ensino médio?,Você se envolve com política?,Como se considera politicamente?,Que área compreende o curso que deseja fazer/faz na faculdade?,...,Quão sensível você é?,Você costuma cobrar seus alunos?,Você é competitivo?,Você é aberto a mudanças? ou é mais resistente?,Você costuma passar simulados pros alunos?,Você recebe apoio da sua família?,você costuma conversar com seus alunos sobre a vida pessoal deles ou só estudos?,Quão bom você é em motivar seus alunos?,Qual problema você é mais apto a ajudar os seus alunos a resolver?,Você tem problemas em receber alunos de sexo diferente?
0,Davi,20,Masculino,Motiva,Cristianismo,Sim,5,"Não, prefiro focar em outras coisas.",Centro,Saúde,...,5,Sim,Talvez,Aberto,Sim,Sim,Os dois,8,Procrastinação,Não

* First of all we will need to name the equivalent columns as the same

In [27]:
df_columns = df_students_answered.columns
df_assessores_columns = df_assessores.columns

* The attributes Aluno,tempo and compatibility are specific for the students. We are only going to use the attributes that are common to both.

In [28]:
df_columns

Index(['Assessor', 'Aluno', 'tempo', 'Idade', 'Gênero',
       'Quão compatível com seu assessor você se considera?',
       'Onde fez/faz ensino médio?', 'Alguma religião?', 'Gosta de esportes?',
       'Como foi/está sendo a qualidade de seu ensino médio?',
       'Você se envolve com política?', 'Como se considera politicamente?',
       'Que área compreende o curso que deseja fazer na faculdade?',
       'Qual sua área preferida no ENEM?', 'Quantos irmãos você tem?',
       'Tem ou já teve algum problema de saúde físico?',
       'Tem ou já teve algum problema de saúde mental?',
       'Pretende fazer faculdade na paraíba?',
       'Pratica atividade física com frequência?',
       'Introvertido ou extrovertido?', 'No tempo livre prefere:',
       'Tem facilidade em fazer amizades?',
       'Que tipo de assessor prefere? mais técnico ou que lide melhor com seu emocional?',
       'Quantas vezes já fez enem? (sem contar como treineiro)',
       'Você se considera uma pessoa paciente?', 'Você é organizado?',
       'Quão sensível você é?', 'Você gosta de ser cobrado?',
       'Você é competitivo?',
       'Você é aberto a mudanças? ou é mais resistente?',
       'Você gosta de fazer simulado?', 'Você recebe apoio da sua família?',
       'Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?',
       'Quão motivado você está?', 'Qual é seu maior problema?',
       'Você prefere um assessor do mesmo sexo?'],
      dtype='object')

In [29]:
df_assessores_columns

Index(['Quem é você?', 'Idade', 'Gênero', 'Onde fez ensino médio?',
       'Alguma religião?', 'Gosta de esportes?',
       'Como foi a qualidade de seu ensino médio?',
       'Você se envolve com política?', 'Como se considera politicamente?',
       'Que área compreende o curso que deseja fazer/faz na faculdade?',
       'Qual sua área preferida no ENEM?', 'Quantos irmãos você tem?',
       'Tem ou já teve algum problema de saúde físico?',
       'Tem ou já teve algum problema de saúde mental?',
       'tem experiência com vestibulares mais tradicionais e de outros estados?',
       'Pratica atividade física com frequência?',
       'Introvertido ou extrovertido?', 'No tempo livre prefere:',
       'Tem facilidade em fazer amizades?', 'Que tipo de assessor você é?',
       'Quantas vezes já fez enem? (sem contar como treineiro)',
       'Você se considera uma pessoa paciente?', 'Você é organizado?',
       'Quão sensível você é?', 'Você costuma cobrar seus alunos?',
       'Você é competitivo?',
       'Você é aberto a mudanças? ou é mais resistente?',
       'Você costuma passar simulados pros alunos?',
       'Você recebe apoio da sua família?',
       'você costuma conversar com seus alunos sobre a vida pessoal deles ou só estudos?',
       'Quão bom você é em motivar seus alunos?',
       'Qual problema você é mais apto a ajudar os seus alunos a resolver?',
       'Você tem problemas em receber alunos de sexo diferente?'],
      dtype='object')

* Since all the advisors questions are in order, we will use it as a dictionary to know which question we are dealing with.

In [30]:
questions_dict = dict(zip(range(len(df_assessores_columns)), df_assessores_columns))
questions_dict

{0: 'Quem é você?',
 1: 'Idade',
 2: 'Gênero',
 3: 'Onde fez ensino médio?',
 4: 'Alguma religião?',
 5: 'Gosta de esportes?',
 6: 'Como foi a qualidade de seu ensino médio?',
 7: 'Você se envolve com política?',
 8: 'Como se considera politicamente?',
 9: 'Que área compreende o curso que deseja fazer/faz na faculdade?',
 10: 'Qual sua área preferida no ENEM?',
 11: 'Quantos irmãos você tem?',
 12: 'Tem ou já teve algum problema de saúde físico?',
 13: 'Tem ou já teve algum problema de saúde mental?',
 14: 'tem experiência com vestibulares mais tradicionais e de outros estados?',
 15: 'Pratica atividade física com frequência?',
 16: 'Introvertido ou extrovertido?',
 17: 'No tempo livre prefere:',
 18: 'Tem facilidade em fazer amizades?',
 19: 'Que tipo de assessor você é?',
 20: 'Quantas vezes já fez enem? (sem contar como treineiro)',
 21: 'Você se considera uma pessoa paciente?',
 22: 'Você é organizado?',
 23: 'Quão sensível você é?',
 24: 'Você costuma cobrar seus alunos?',
 25: 'Você é competitivo?',
 26: 'Você é aberto a mudanças? ou é mais resistente?',
 27: 'Você costuma passar simulados pros alunos?',
 28: 'Você recebe apoio da sua família?',
 29: 'você costuma conversar com seus alunos sobre a vida pessoal deles ou só estudos?',
 30: 'Quão bom você é em motivar seus alunos?',
 31: 'Qual problema você é mais apto a ajudar os seus alunos a resolver?',
 32: 'Você tem problemas em receber alunos de sexo diferente?'}

* to make it easier, we will use numbers instead of questions

In [31]:
df_columns_new = [0, 'Aluno', 'tempo', 1, 2,
       'Quão compatível com seu assessor você se considera?',
       3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
              28, 29, 30, 31, 32]

In [32]:
df_assessores_columns_new = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
                        20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]

* Adding the new columns to the previous dataframes

In [33]:
df_students_answered.columns = df_columns_new

In [34]:
df_assessores.columns = df_assessores_columns_new

In [35]:
df_students_answered.head(1)

,0,Aluno,tempo,1,2,Quão compatível com seu assessor você se considera?,3,4,5,6,...,23,24,25,26,27,28,29,30,31,32
0,Ariel,Adriel Ribeiro,3,18.0,Masculino,8.0,Motiva,Cristianismo,Sim,5.0,...,3.0,Não,Talvez,Aberto,Sim,Sim,Os dois,8.0,Procrastinação,"sim, fico mais confortável"

* adding the aluno colum as index

In [36]:
df_students_answered.index = df_students_answered.Aluno

In [37]:
df_students_answered.head(1)

,0,Aluno,tempo,1,2,Quão compatível com seu assessor você se considera?,3,4,5,6,...,23,24,25,26,27,28,29,30,31,32
Aluno,,,,,,,,,,,,,,,,,,,,,
Adriel Ribeiro,Ariel,Adriel Ribeiro,3,18.0,Masculino,8.0,Motiva,Cristianismo,Sim,5.0,...,3.0,Não,Talvez,Aberto,Sim,Sim,Os dois,8.0,Procrastinação,"sim, fico mais confortável"

In [38]:
df_assessores.head(1)

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,Davi,20,Masculino,Motiva,Cristianismo,Sim,5,"Não, prefiro focar em outras coisas.",Centro,Saúde,...,5,Sim,Talvez,Aberto,Sim,Sim,Os dois,8,Procrastinação,Não

* adding the 0 index (advisor) column as index

In [39]:
df_assessores.index = df_assessores[0]

In [40]:
df_assessores.head()

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,,,,,,,,,,,,,,,,,,,,,
Davi,Davi,20,Masculino,Motiva,Cristianismo,Sim,5,"Não, prefiro focar em outras coisas.",Centro,Saúde,...,5,Sim,Talvez,Aberto,Sim,Sim,Os dois,8,Procrastinação,Não
Lorenna,Lorenna,20,Feminino,Motiva,Agnóstico,Sim,4,"Não, prefiro focar em outras coisas.",Esquerda,Saúde,...,7,Sim,Sim,Aberto,Sim,mais ou menos,Os dois,9,Procrastinação,Não
Rayssa,Rayssa,23,Feminino,Motiva,Cristianismo,Não,5,"Não, prefiro focar em outras coisas.",Direita,Saúde,...,6,Sim,Sim,Aberto,Sim,Sim,Os dois,5,Dedicação,Não
Débora,Débora,20,Feminino,Outro em João Pessoa,Cristianismo,Sim,3,"Sim, acho importante.",Esquerda,Saúde,...,4,Sim,Sim,Aberto,Sim,Sim,Os dois,7,Dedicação,Não
Glaucielle,Glaucielle,24,Feminino,Outro em João Pessoa,Cristianismo,Sim,3,"Sim, acho importante.",Esquerda,Saúde,...,8,Sim,Talvez,Aberto,Sim,Sim,Os dois,9,Procrastinação,Não

## creating the correlations between both quiz responses in order to compute the compability

* In this section we will examine column by column how the variables relate to each other. Some of them have are positive if both are the same and some are not.

### Age

In [41]:
questions_dict[1]

'Idade'

* In this first section we are going to use it as a restriction. As no advisor should be responsible for a student that is 2 years older than him. So, in any case that this is not satisfacted, we will put a negative compatibility.

In order to do so, we will use the following dataframes:
1. compatibility_matrix
2. df
3. df_assessores

In [42]:
compatibility_matrix['Ariel']["Adriel Ribeiro"]

0

In [43]:
int(df_students_answered.loc['Adriel Ribeiro'][1]) == 18

True

In [44]:
df_assessores.loc['Eduardo'][1]

24

In [45]:
for advisor in df_assessores[0]:
    advisor_age = int(df_assessores.loc[advisor][1])
    for student in df_students_answered.Aluno:
        student_age = int(df_students_answered.loc[student][1])
        if advisor_age >= 22:
            print(advisor,student)
            if student_age < 17:
                compatibility_matrix[advisor][student] = -1
        else:
            if (advisor_age + 1 < student_age):
                compatibility_matrix[advisor][student] = -1

Rayssa Adriel Ribeiro
Rayssa Breno Alves Amorim
Rayssa Gabriel Almeida
Rayssa Ivinyn Pessoa Freire Soares
Rayssa Mariana Amorim
Rayssa Natália de Brito Lima
Rayssa Renan Vieira Costa
Rayssa Rivaldo Ferreira de Freitas Filho
Rayssa Alice de Oliveira Maia
Rayssa Ana Karenina Barreto Amorim Pessoa
Rayssa Anne Gabrielle de Sousa Diniz
Rayssa Beatriz Diniz
Rayssa Camilla Ellen Crispim de Felix Nobrega
Rayssa Camilla Queiroz Ferreira
Rayssa Gabriella Gomes Ferreira gadelha
Rayssa Manuella Freire
Rayssa Myllena Enmyly Ferreira de Almeida
Rayssa Rafaela Maria Ribera Gonçalves de Souza
Rayssa Vitória Gouveia Gomes
Rayssa maria eduarda sarmento lucena
Rayssa Anna Beatriz de S.Ayres
Rayssa Daniela Freitas
Rayssa João Manoel Medeiros Oliveira Di Lorenzo
Rayssa Maitê Maria de Souza Veras
Rayssa Maria Fernanda Rodrigues Gomes
Rayssa Maria Laura de Carvalho Pinto
Rayssa Rebeca Ferrer Cruz
Rayssa Ana Luísa Campos Porpino
Rayssa Antonio Inacio Pimentel Rodrigues de Lemos Filho
Rayssa Arthur Moreira Meirelles
Rayssa Caio robson gomes luna cruz
Rayssa Elio Ribeiro de Morais Filho
Rayssa Joao Paulo Rodrigues
Rayssa José Vicente Abrantes Gadelha Neto
Rayssa Maria Eduarda Sales Freire
Rayssa Matheus correia
Rayssa Milena Nóbrega Albuquerque
Rayssa Samuel Gomes
Rayssa Tayane Ysla Medeiros Gomes
Rayssa Washington Filho
Rayssa joão max nogueira de andrade
Rayssa thalita tayana dantas de sousa
Rayssa Ana Luisa Londres Gomes Lins
Rayssa Déborah Maria Coutinho Alves
Rayssa Elaine Andrielly Monteiro da Silva
Rayssa Giovana Costa Dias Lins
Rayssa Júlia Duarte Andrade Oliveira
Rayssa Laryssa Gonçalves Couras
Rayssa Letícia Leandra de Castro Cunha
Rayssa Luísa Sabino Florêncio
Rayssa Lívia França Tenório Pinheiro
Rayssa Maria Cecília Maranhão Ribeiro
Rayssa Maria Clara Campelo Galvão Rodrigues
Rayssa Maria Eduarda Nóbrega Honório de Assis
Rayssa Maria Eduarda de Souza Nery Nascimento
Rayssa Monise Carvalho Nascimento
Rayssa Sophia Medeiros Bueno
Rayssa Alexander Viana Fragoso Junior
Rayssa Ana Beatriz Souza Lira Carneiro da Cunha
Rayssa Catharina Louise A. de Oliveira
Rayssa Gabriela Cristina de Oliveira Gouveia
Rayssa Heyell Kevin
Rayssa João Victor Oliveira Estrela
Rayssa Laís Maria P. de Sousa
Rayssa Luiza Medeiros
Rayssa Tainá Martins Costa Ferreira Silva
Rayssa Beatriz Vilhena Camara Menezes
Rayssa Hanna Diniz
Rayssa Júlia Gonçalves Gadelha
Rayssa Mariana Mello de Farias
Rayssa Adrya Catharinne Santos Sousa da Silva
Rayssa Ana Luíza Gomes de Lacerda Quintans
Rayssa Camille Gabrielly Araújo Jucá
Rayssa Eduardo Paulo Queiroz Torres
Rayssa Francisco Gomes de Freitas Junior
Rayssa Giuliana Felipe da Silva
Rayssa Isadora Ferraz
Rayssa Julia Barros barbosa
Rayssa Larissa Vinesof
Rayssa Maria Clara Gomes de Lacerda Quintans e Magalhães
Rayssa Maria Clara Oliveira Nascimento
Rayssa Maria Eduarda Morais Candeia
Rayssa Mateus Gualberto
Rayssa Otto Nóbrega Hofmann
Rayssa Thayná Maria Tavares de Oliveira
Rayssa Carolina W.Q.F Evangelista
Rayssa Gabriela Arnaud Bandeira
Rayssa Karolina Azevedo Bringel
Rayssa Letícia Meira
Rayssa Letícia de Oliveira Barreto
Rayssa Maria Eduarda Franco Londres
Rayssa Maria Eduarda de Azevedo Galdino b s
Rayssa Maria Luísa Dantas Teixeira de Carvalho Rocha
Rayssa Maria Paula Braga
Rayssa Nicole Cavalcanti Pereira
Rayssa Raissa Nóbrega Cordeiro
Rayssa Thainá Maria Vieira de Andrade
Rayssa Ana Beatriz de Freitas Coutinho
Rayssa Beatriz d'Avila Lins Lacerda
Rayssa Clarissa Frazão
Rayssa Fernanda de Queiroz Albuquerque
Rayssa Gabriel Bandeira
Rayssa Gabriele Guerra
Rayssa Geórgia Campos Perdigão
Rayssa Gonzalo Alonso Medeiros Bueno
Rayssa Henrique Fialho Carneiro Braga Costa
Rayssa Luana de Sá Mendes
Rayssa Lucas toscano
Rayssa Luiz Henrique Cartaxo Fernandes
Rayssa Paula Fechine
Rayssa Rodrigo Carneiro Meira Lima
Rayssa Ana Carolina Correia Magalhaes
Rayssa Ana Flávia Cartaxo Moura Rodrigues de Aquino
Rayssa Letícia Andrade de Almeida
Rayssa Livia Beatriz Estrela De Oliveira
Rayssa Luana Toscano Pereira Henriques Ribeiro
Rayssa Marcela Vitória
Rayssa Maria Alice de Sena Morais
Rayssa Maria Beatriz de Melo Queiroz
Rayssa Maria Eduarda Souza Minéo
Rayssa Maria Luísa Mendes Abrantes
Rayssa Ana Luísa Vasconcelos
Rayssa Danillo Fernandes Lira Dias
Rayssa José Ricardo Brito Pereira Segundo
Rayssa Maria Eduarda Souza Malheiros Feliciano
Rayssa Pedro Henrique de Castro Pinto Almeida
Rayssa Pedro Machado Lago
Rayssa Raquel Nobrega do Nascimento
Rayssa Rodrigo Medeiros Delgado
Rayssa Sofia Leite de Araújo
Rayssa Arthur Pessoa Travassos Vinagre
Rayssa Carlos Alberto De Assis Madruga Filho
Rayssa Fernando Amorim Pontes Neto
Rayssa Giulia Lopes Carvalho
Rayssa Giulia Nóbrega Coutinho
Rayssa Herculano Galvão
Rayssa José Nidival de Queiróz Júnior
Rayssa Matheus Henrique Oliveira da Nóbrega
Rayssa Neto
Rayssa Samuel Lemos
Rayssa Victor Holmes trindade Rocha
Rayssa Yohanna Kalynna Santos Wanderley
Rayssa Alexia Sampaio Menezes
Rayssa Ivaldo Aurélio
Rayssa Julianna Ventura Pereira
Rayssa Lara Pereira
Rayssa Lucca Nuto França De Albuquerque
Rayssa Maria Fernanda Moura de Lima
Rayssa Maryanahdantas@hotmail.com
Rayssa Ana caroline Gomes de Miranda Linhares
Rayssa Bruno Chianca Heim Teotonio
Rayssa Carlos Henrique Rocha
Rayssa Gabriela Rocha Jorge
Rayssa Luana Maria Teixeira de Carvalho Pessoa de Souza
Rayssa Maria Fernanda Aguiar R Coutinho
Rayssa Nathan Marlon Ferreira Carreiro
Rayssa Sophia Adelino Xavier Pontes de Freitas
Glaucielle Adriel Ribeiro
Glaucielle Breno Alves Amorim
Glaucielle Gabriel Almeida
Glaucielle Ivinyn Pessoa Freire Soares
Glaucielle Mariana Amorim
Glaucielle Natália de Brito Lima
Glaucielle Renan Vieira Costa
Glaucielle Rivaldo Ferreira de Freitas Filho
Glaucielle Alice de Oliveira Maia
Glaucielle Ana Karenina Barreto Amorim Pessoa
Glaucielle Anne Gabrielle de Sousa Diniz
Glaucielle Beatriz Diniz
Glaucielle Camilla Ellen Crispim de Felix Nobrega
Glaucielle Camilla Queiroz Ferreira
Glaucielle Gabriella Gomes Ferreira gadelha
Glaucielle Manuella Freire
Glaucielle Myllena Enmyly Ferreira de Almeida
Glaucielle Rafaela Maria Ribera Gonçalves de Souza
Glaucielle Vitória Gouveia Gomes
Glaucielle maria eduarda sarmento lucena
Glaucielle Anna Beatriz de S.Ayres
Glaucielle Daniela Freitas
Glaucielle João Manoel Medeiros Oliveira Di Lorenzo
Glaucielle Maitê Maria de Souza Veras
Glaucielle Maria Fernanda Rodrigues Gomes
Glaucielle Maria Laura de Carvalho Pinto
Glaucielle Rebeca Ferrer Cruz
Glaucielle Ana Luísa Campos Porpino
Glaucielle Antonio Inacio Pimentel Rodrigues de Lemos Filho
Glaucielle Arthur Moreira Meirelles
Glaucielle Caio robson gomes luna cruz
Glaucielle Elio Ribeiro de Morais Filho
Glaucielle Joao Paulo Rodrigues
Glaucielle José Vicente Abrantes Gadelha Neto
Glaucielle Maria Eduarda Sales Freire
Glaucielle Matheus correia
Glaucielle Milena Nóbrega Albuquerque
Glaucielle Samuel Gomes
Glaucielle Tayane Ysla Medeiros Gomes
Glaucielle Washington Filho
Glaucielle joão max nogueira de andrade
Glaucielle thalita tayana dantas de sousa
Glaucielle Ana Luisa Londres Gomes Lins
Glaucielle Déborah Maria Coutinho Alves
Glaucielle Elaine Andrielly Monteiro da Silva
Glaucielle Giovana Costa Dias Lins
Glaucielle Júlia Duarte Andrade Oliveira
Glaucielle Laryssa Gonçalves Couras
Glaucielle Letícia Leandra de Castro Cunha
Glaucielle Luísa Sabino Florêncio
Glaucielle Lívia França Tenório Pinheiro
Glaucielle Maria Cecília Maranhão Ribeiro
Glaucielle Maria Clara Campelo Galvão Rodrigues
Glaucielle Maria Eduarda Nóbrega Honório de Assis
Glaucielle Maria Eduarda de Souza Nery Nascimento
Glaucielle Monise Carvalho Nascimento
Glaucielle Sophia Medeiros Bueno
Glaucielle Alexander Viana Fragoso Junior
Glaucielle Ana Beatriz Souza Lira Carneiro da Cunha
Glaucielle Catharina Louise A. de Oliveira
Glaucielle Gabriela Cristina de Oliveira Gouveia
Glaucielle Heyell Kevin
Glaucielle João Victor Oliveira Estrela
Glaucielle Laís Maria P. de Sousa
Glaucielle Luiza Medeiros
Glaucielle Tainá Martins Costa Ferreira Silva
Glaucielle Beatriz Vilhena Camara Menezes
Glaucielle Hanna Diniz
Glaucielle Júlia Gonçalves Gadelha
Glaucielle Mariana Mello de Farias
Glaucielle Adrya Catharinne Santos Sousa da Silva
Glaucielle Ana Luíza Gomes de Lacerda Quintans
Glaucielle Camille Gabrielly Araújo Jucá
Glaucielle Eduardo Paulo Queiroz Torres
Glaucielle Francisco Gomes de Freitas Junior
Glaucielle Giuliana Felipe da Silva
Glaucielle Isadora Ferraz
Glaucielle Julia Barros barbosa
Glaucielle Larissa Vinesof
Glaucielle Maria Clara Gomes de Lacerda Quintans e Magalhães
Glaucielle Maria Clara Oliveira Nascimento
Glaucielle Maria Eduarda Morais Candeia
Glaucielle Mateus Gualberto
Glaucielle Otto Nóbrega Hofmann
Glaucielle Thayná Maria Tavares de Oliveira
Glaucielle Carolina W.Q.F Evangelista
Glaucielle Gabriela Arnaud Bandeira
Glaucielle Karolina Azevedo Bringel
Glaucielle Letícia Meira
Glaucielle Letícia de Oliveira Barreto
Glaucielle Maria Eduarda Franco Londres
Glaucielle Maria Eduarda de Azevedo Galdino b s
Glaucielle Maria Luísa Dantas Teixeira de Carvalho Rocha
Glaucielle Maria Paula Braga
Glaucielle Nicole Cavalcanti Pereira
Glaucielle Raissa Nóbrega Cordeiro
Glaucielle Thainá Maria Vieira de Andrade
Glaucielle Ana Beatriz de Freitas Coutinho
Glaucielle Beatriz d'Avila Lins Lacerda
Glaucielle Clarissa Frazão
Glaucielle Fernanda de Queiroz Albuquerque
Glaucielle Gabriel Bandeira
Glaucielle Gabriele Guerra
Glaucielle Geórgia Campos Perdigão
Glaucielle Gonzalo Alonso Medeiros Bueno
Glaucielle Henrique Fialho Carneiro Braga Costa
Glaucielle Luana de Sá Mendes
Glaucielle Lucas toscano
Glaucielle Luiz Henrique Cartaxo Fernandes
Glaucielle Paula Fechine
Glaucielle Rodrigo Carneiro Meira Lima
Glaucielle Ana Carolina Correia Magalhaes
Glaucielle Ana Flávia Cartaxo Moura Rodrigues de Aquino
Glaucielle Letícia Andrade de Almeida
Glaucielle Livia Beatriz Estrela De Oliveira
Glaucielle Luana Toscano Pereira Henriques Ribeiro
Glaucielle Marcela Vitória
Glaucielle Maria Alice de Sena Morais
Glaucielle Maria Beatriz de Melo Queiroz
Glaucielle Maria Eduarda Souza Minéo
Glaucielle Maria Luísa Mendes Abrantes
Glaucielle Ana Luísa Vasconcelos
Glaucielle Danillo Fernandes Lira Dias
Glaucielle José Ricardo Brito Pereira Segundo
Glaucielle Maria Eduarda Souza Malheiros Feliciano
Glaucielle Pedro Henrique de Castro Pinto Almeida
Glaucielle Pedro Machado Lago
Glaucielle Raquel Nobrega do Nascimento
Glaucielle Rodrigo Medeiros Delgado
Glaucielle Sofia Leite de Araújo
Glaucielle Arthur Pessoa Travassos Vinagre
Glaucielle Carlos Alberto De Assis Madruga Filho
Glaucielle Fernando Amorim Pontes Neto
Glaucielle Giulia Lopes Carvalho
Glaucielle Giulia Nóbrega Coutinho
Glaucielle Herculano Galvão
Glaucielle José Nidival de Queiróz Júnior
Glaucielle Matheus Henrique Oliveira da Nóbrega
Glaucielle Neto
Glaucielle Samuel Lemos
Glaucielle Victor Holmes trindade Rocha
Glaucielle Yohanna Kalynna Santos Wanderley
Glaucielle Alexia Sampaio Menezes
Glaucielle Ivaldo Aurélio
Glaucielle Julianna Ventura Pereira
Glaucielle Lara Pereira
Glaucielle Lucca Nuto França De Albuquerque
Glaucielle Maria Fernanda Moura de Lima
Glaucielle Maryanahdantas@hotmail.com
Glaucielle Ana caroline Gomes de Miranda Linhares
Glaucielle Bruno Chianca Heim Teotonio
Glaucielle Carlos Henrique Rocha
Glaucielle Gabriela Rocha Jorge
Glaucielle Luana Maria Teixeira de Carvalho Pessoa de Souza
Glaucielle Maria Fernanda Aguiar R Coutinho
Glaucielle Nathan Marlon Ferreira Carreiro
Glaucielle Sophia Adelino Xavier Pontes de Freitas
Patriota Adriel Ribeiro
Patriota Breno Alves Amorim
Patriota Gabriel Almeida
Patriota Ivinyn Pessoa Freire Soares
Patriota Mariana Amorim
Patriota Natália de Brito Lima
Patriota Renan Vieira Costa
Patriota Rivaldo Ferreira de Freitas Filho
Patriota Alice de Oliveira Maia
Patriota Ana Karenina Barreto Amorim Pessoa
Patriota Anne Gabrielle de Sousa Diniz
Patriota Beatriz Diniz
Patriota Camilla Ellen Crispim de Felix Nobrega
Patriota Camilla Queiroz Ferreira
Patriota Gabriella Gomes Ferreira gadelha
Patriota Manuella Freire
Patriota Myllena Enmyly Ferreira de Almeida
Patriota Rafaela Maria Ribera Gonçalves de Souza
Patriota Vitória Gouveia Gomes
Patriota maria eduarda sarmento lucena
Patriota Anna Beatriz de S.Ayres
Patriota Daniela Freitas
Patriota João Manoel Medeiros Oliveira Di Lorenzo
Patriota Maitê Maria de Souza Veras
Patriota Maria Fernanda Rodrigues Gomes
Patriota Maria Laura de Carvalho Pinto
Patriota Rebeca Ferrer Cruz
Patriota Ana Luísa Campos Porpino
Patriota Antonio Inacio Pimentel Rodrigues de Lemos Filho
Patriota Arthur Moreira Meirelles
Patriota Caio robson gomes luna cruz
Patriota Elio Ribeiro de Morais Filho
Patriota Joao Paulo Rodrigues
Patriota José Vicente Abrantes Gadelha Neto
Patriota Maria Eduarda Sales Freire
Patriota Matheus correia
Patriota Milena Nóbrega Albuquerque
Patriota Samuel Gomes
Patriota Tayane Ysla Medeiros Gomes
Patriota Washington Filho
Patriota joão max nogueira de andrade
Patriota thalita tayana dantas de sousa
Patriota Ana Luisa Londres Gomes Lins
Patriota Déborah Maria Coutinho Alves
Patriota Elaine Andrielly Monteiro da Silva
Patriota Giovana Costa Dias Lins
Patriota Júlia Duarte Andrade Oliveira
Patriota Laryssa Gonçalves Couras
Patriota Letícia Leandra de Castro Cunha
Patriota Luísa Sabino Florêncio
Patriota Lívia França Tenório Pinheiro
Patriota Maria Cecília Maranhão Ribeiro
Patriota Maria Clara Campelo Galvão Rodrigues
Patriota Maria Eduarda Nóbrega Honório de Assis
Patriota Maria Eduarda de Souza Nery Nascimento
Patriota Monise Carvalho Nascimento
Patriota Sophia Medeiros Bueno
Patriota Alexander Viana Fragoso Junior
Patriota Ana Beatriz Souza Lira Carneiro da Cunha
Patriota Catharina Louise A. de Oliveira
Patriota Gabriela Cristina de Oliveira Gouveia
Patriota Heyell Kevin
Patriota João Victor Oliveira Estrela
Patriota Laís Maria P. de Sousa
Patriota Luiza Medeiros
Patriota Tainá Martins Costa Ferreira Silva
Patriota Beatriz Vilhena Camara Menezes
Patriota Hanna Diniz
Patriota Júlia Gonçalves Gadelha
Patriota Mariana Mello de Farias
Patriota Adrya Catharinne Santos Sousa da Silva
Patriota Ana Luíza Gomes de Lacerda Quintans
Patriota Camille Gabrielly Araújo Jucá
Patriota Eduardo Paulo Queiroz Torres
Patriota Francisco Gomes de Freitas Junior
Patriota Giuliana Felipe da Silva
Patriota Isadora Ferraz
Patriota Julia Barros barbosa
Patriota Larissa Vinesof
Patriota Maria Clara Gomes de Lacerda Quintans e Magalhães
Patriota Maria Clara Oliveira Nascimento
Patriota Maria Eduarda Morais Candeia
Patriota Mateus Gualberto
Patriota Otto Nóbrega Hofmann
Patriota Thayná Maria Tavares de Oliveira
Patriota Carolina W.Q.F Evangelista
Patriota Gabriela Arnaud Bandeira
Patriota Karolina Azevedo Bringel
Patriota Letícia Meira
Patriota Letícia de Oliveira Barreto
Patriota Maria Eduarda Franco Londres
Patriota Maria Eduarda de Azevedo Galdino b s
Patriota Maria Luísa Dantas Teixeira de Carvalho Rocha
Patriota Maria Paula Braga
Patriota Nicole Cavalcanti Pereira
Patriota Raissa Nóbrega Cordeiro
Patriota Thainá Maria Vieira de Andrade
Patriota Ana Beatriz de Freitas Coutinho
Patriota Beatriz d'Avila Lins Lacerda
Patriota Clarissa Frazão
Patriota Fernanda de Queiroz Albuquerque
Patriota Gabriel Bandeira
Patriota Gabriele Guerra
Patriota Geórgia Campos Perdigão
Patriota Gonzalo Alonso Medeiros Bueno
Patriota Henrique Fialho Carneiro Braga Costa
Patriota Luana de Sá Mendes
Patriota Lucas toscano
Patriota Luiz Henrique Cartaxo Fernandes
Patriota Paula Fechine
Patriota Rodrigo Carneiro Meira Lima
Patriota Ana Carolina Correia Magalhaes
Patriota Ana Flávia Cartaxo Moura Rodrigues de Aquino
Patriota Letícia Andrade de Almeida
Patriota Livia Beatriz Estrela De Oliveira
Patriota Luana Toscano Pereira Henriques Ribeiro
Patriota Marcela Vitória
Patriota Maria Alice de Sena Morais
Patriota Maria Beatriz de Melo Queiroz
Patriota Maria Eduarda Souza Minéo
Patriota Maria Luísa Mendes Abrantes
Patriota Ana Luísa Vasconcelos
Patriota Danillo Fernandes Lira Dias
Patriota José Ricardo Brito Pereira Segundo
Patriota Maria Eduarda Souza Malheiros Feliciano
Patriota Pedro Henrique de Castro Pinto Almeida
Patriota Pedro Machado Lago
Patriota Raquel Nobrega do Nascimento
Patriota Rodrigo Medeiros Delgado
Patriota Sofia Leite de Araújo
Patriota Arthur Pessoa Travassos Vinagre
Patriota Carlos Alberto De Assis Madruga Filho
Patriota Fernando Amorim Pontes Neto
Patriota Giulia Lopes Carvalho
Patriota Giulia Nóbrega Coutinho
Patriota Herculano Galvão
Patriota José Nidival de Queiróz Júnior
Patriota Matheus Henrique Oliveira da Nóbrega
Patriota Neto
Patriota Samuel Lemos
Patriota Victor Holmes trindade Rocha
Patriota Yohanna Kalynna Santos Wanderley
Patriota Alexia Sampaio Menezes
Patriota Ivaldo Aurélio
Patriota Julianna Ventura Pereira
Patriota Lara Pereira
Patriota Lucca Nuto França De Albuquerque
Patriota Maria Fernanda Moura de Lima
Patriota Maryanahdantas@hotmail.com
Patriota Ana caroline Gomes de Miranda Linhares
Patriota Bruno Chianca Heim Teotonio
Patriota Carlos Henrique Rocha
Patriota Gabriela Rocha Jorge
Patriota Luana Maria Teixeira de Carvalho Pessoa de Souza
Patriota Maria Fernanda Aguiar R Coutinho
Patriota Nathan Marlon Ferreira Carreiro
Patriota Sophia Adelino Xavier Pontes de Freitas

Carolzinha Adriel Ribeiro
Carolzinha Breno Alves Amorim
Carolzinha Gabriel Almeida
Carolzinha Ivinyn Pessoa Freire Soares
Carolzinha Mariana Amorim
Carolzinha Natália de Brito Lima
Carolzinha Renan Vieira Costa
Carolzinha Rivaldo Ferreira de Freitas Filho
Carolzinha Alice de Oliveira Maia
Carolzinha Ana Karenina Barreto Amorim Pessoa
Carolzinha Anne Gabrielle de Sousa Diniz
Carolzinha Beatriz Diniz
Carolzinha Camilla Ellen Crispim de Felix Nobrega
Carolzinha Camilla Queiroz Ferreira
Carolzinha Gabriella Gomes Ferreira gadelha
Carolzinha Manuella Freire
Carolzinha Myllena Enmyly Ferreira de Almeida
Carolzinha Rafaela Maria Ribera Gonçalves de Souza
Carolzinha Vitória Gouveia Gomes
Carolzinha maria eduarda sarmento lucena
Carolzinha Anna Beatriz de S.Ayres
Carolzinha Daniela Freitas
Carolzinha João Manoel Medeiros Oliveira Di Lorenzo
Carolzinha Maitê Maria de Souza Veras
Carolzinha Maria Fernanda Rodrigues Gomes
Carolzinha Maria Laura de Carvalho Pinto
Carolzinha Rebeca Ferrer Cruz
Carolzinha Ana Luísa Campos Porpino
Carolzinha Antonio Inacio Pimentel Rodrigues de Lemos Filho
Carolzinha Arthur Moreira Meirelles
Carolzinha Caio robson gomes luna cruz
Carolzinha Elio Ribeiro de Morais Filho
Carolzinha Joao Paulo Rodrigues
Carolzinha José Vicente Abrantes Gadelha Neto
Carolzinha Maria Eduarda Sales Freire
Carolzinha Matheus correia
Carolzinha Milena Nóbrega Albuquerque
Carolzinha Samuel Gomes
Carolzinha Tayane Ysla Medeiros Gomes
Carolzinha Washington Filho
Carolzinha joão max nogueira de andrade
Carolzinha thalita tayana dantas de sousa
Carolzinha Ana Luisa Londres Gomes Lins
Carolzinha Déborah Maria Coutinho Alves
Carolzinha Elaine Andrielly Monteiro da Silva
Carolzinha Giovana Costa Dias Lins
Carolzinha Júlia Duarte Andrade Oliveira
Carolzinha Laryssa Gonçalves Couras
Carolzinha Letícia Leandra de Castro Cunha
Carolzinha Luísa Sabino Florêncio
Carolzinha Lívia França Tenório Pinheiro
Carolzinha Maria Cecília Maranhão Ribeiro
Carolzinha Maria Clara Campelo Galvão Rodrigues
Carolzinha Maria Eduarda Nóbrega Honório de Assis
Carolzinha Maria Eduarda de Souza Nery Nascimento
Carolzinha Monise Carvalho Nascimento
Carolzinha Sophia Medeiros Bueno
Carolzinha Alexander Viana Fragoso Junior
Carolzinha Ana Beatriz Souza Lira Carneiro da Cunha
Carolzinha Catharina Louise A. de Oliveira
Carolzinha Gabriela Cristina de Oliveira Gouveia
Carolzinha Heyell Kevin
Carolzinha João Victor Oliveira Estrela
Carolzinha Laís Maria P. de Sousa
Carolzinha Luiza Medeiros
Carolzinha Tainá Martins Costa Ferreira Silva
Carolzinha Beatriz Vilhena Camara Menezes
Carolzinha Hanna Diniz
Carolzinha Júlia Gonçalves Gadelha
Carolzinha Mariana Mello de Farias
Carolzinha Adrya Catharinne Santos Sousa da Silva
Carolzinha Ana Luíza Gomes de Lacerda Quintans
Carolzinha Camille Gabrielly Araújo Jucá
Carolzinha Eduardo Paulo Queiroz Torres
Carolzinha Francisco Gomes de Freitas Junior
Carolzinha Giuliana Felipe da Silva
Carolzinha Isadora Ferraz
Carolzinha Julia Barros barbosa
Carolzinha Larissa Vinesof
Carolzinha Maria Clara Gomes de Lacerda Quintans e Magalhães
Carolzinha Maria Clara Oliveira Nascimento
Carolzinha Maria Eduarda Morais Candeia
Carolzinha Mateus Gualberto
Carolzinha Otto Nóbrega Hofmann
Carolzinha Thayná Maria Tavares de Oliveira
Carolzinha Carolina W.Q.F Evangelista
Carolzinha Gabriela Arnaud Bandeira
Carolzinha Karolina Azevedo Bringel
Carolzinha Letícia Meira
Carolzinha Letícia de Oliveira Barreto
Carolzinha Maria Eduarda Franco Londres
Carolzinha Maria Eduarda de Azevedo Galdino b s
Carolzinha Maria Luísa Dantas Teixeira de Carvalho Rocha
Carolzinha Maria Paula Braga
Carolzinha Nicole Cavalcanti Pereira
Carolzinha Raissa Nóbrega Cordeiro
Carolzinha Thainá Maria Vieira de Andrade
Carolzinha Ana Beatriz de Freitas Coutinho
Carolzinha Beatriz d'Avila Lins Lacerda
Carolzinha Clarissa Frazão
Carolzinha Fernanda de Queiroz Albuquerque
Carolzinha Gabriel Bandeira
Carolzinha Gabriele Guerra
Carolzinha Geórgia Campos Perdigão
Carolzinha Gonzalo Alonso Medeiros Bueno
Carolzinha Henrique Fialho Carneiro Braga Costa
Carolzinha Luana de Sá Mendes
Carolzinha Lucas toscano
Carolzinha Luiz Henrique Cartaxo Fernandes
Carolzinha Paula Fechine
Carolzinha Rodrigo Carneiro Meira Lima
Carolzinha Ana Carolina Correia Magalhaes
Carolzinha Ana Flávia Cartaxo Moura Rodrigues de Aquino
Carolzinha Letícia Andrade de Almeida
Carolzinha Livia Beatriz Estrela De Oliveira
Carolzinha Luana Toscano Pereira Henriques Ribeiro
Carolzinha Marcela Vitória
Carolzinha Maria Alice de Sena Morais
Carolzinha Maria Beatriz de Melo Queiroz
Carolzinha Maria Eduarda Souza Minéo
Carolzinha Maria Luísa Mendes Abrantes
Carolzinha Ana Luísa Vasconcelos
Carolzinha Danillo Fernandes Lira Dias
Carolzinha José Ricardo Brito Pereira Segundo
Carolzinha Maria Eduarda Souza Malheiros Feliciano
Carolzinha Pedro Henrique de Castro Pinto Almeida
Carolzinha Pedro Machado Lago
Carolzinha Raquel Nobrega do Nascimento
Carolzinha Rodrigo Medeiros Delgado
Carolzinha Sofia Leite de Araújo
Carolzinha Arthur Pessoa Travassos Vinagre
Carolzinha Carlos Alberto De Assis Madruga Filho
Carolzinha Fernando Amorim Pontes Neto
Carolzinha Giulia Lopes Carvalho
Carolzinha Giulia Nóbrega Coutinho
Carolzinha Herculano Galvão
Carolzinha José Nidival de Queiróz Júnior
Carolzinha Matheus Henrique Oliveira da Nóbrega
Carolzinha Neto
Carolzinha Samuel Lemos
Carolzinha Victor Holmes trindade Rocha
Carolzinha Yohanna Kalynna Santos Wanderley
Carolzinha Alexia Sampaio Menezes
Carolzinha Ivaldo Aurélio
Carolzinha Julianna Ventura Pereira
Carolzinha Lara Pereira
Carolzinha Lucca Nuto França De Albuquerque
Carolzinha Maria Fernanda Moura de Lima
Carolzinha Maryanahdantas@hotmail.com
Carolzinha Ana caroline Gomes de Miranda Linhares
Carolzinha Bruno Chianca Heim Teotonio
Carolzinha Carlos Henrique Rocha
Carolzinha Gabriela Rocha Jorge
Carolzinha Luana Maria Teixeira de Carvalho Pessoa de Souza
Carolzinha Maria Fernanda Aguiar R Coutinho
Carolzinha Nathan Marlon Ferreira Carreiro
Carolzinha Sophia Adelino Xavier Pontes de Freitas
Eduardo Adriel Ribeiro
Eduardo Breno Alves Amorim
Eduardo Gabriel Almeida
Eduardo Ivinyn Pessoa Freire Soares
Eduardo Mariana Amorim
Eduardo Natália de Brito Lima
Eduardo Renan Vieira Costa
Eduardo Rivaldo Ferreira de Freitas Filho
Eduardo Alice de Oliveira Maia
Eduardo Ana Karenina Barreto Amorim Pessoa
Eduardo Anne Gabrielle de Sousa Diniz
Eduardo Beatriz Diniz
Eduardo Camilla Ellen Crispim de Felix Nobrega
Eduardo Camilla Queiroz Ferreira
Eduardo Gabriella Gomes Ferreira gadelha
Eduardo Manuella Freire
Eduardo Myllena Enmyly Ferreira de Almeida
Eduardo Rafaela Maria Ribera Gonçalves de Souza
Eduardo Vitória Gouveia Gomes
Eduardo maria eduarda sarmento lucena
Eduardo Anna Beatriz de S.Ayres
Eduardo Daniela Freitas
Eduardo João Manoel Medeiros Oliveira Di Lorenzo
Eduardo Maitê Maria de Souza Veras
Eduardo Maria Fernanda Rodrigues Gomes
Eduardo Maria Laura de Carvalho Pinto
Eduardo Rebeca Ferrer Cruz
Eduardo Ana Luísa Campos Porpino
Eduardo Antonio Inacio Pimentel Rodrigues de Lemos Filho
Eduardo Arthur Moreira Meirelles
Eduardo Caio robson gomes luna cruz
Eduardo Elio Ribeiro de Morais Filho
Eduardo Joao Paulo Rodrigues
Eduardo José Vicente Abrantes Gadelha Neto
Eduardo Maria Eduarda Sales Freire
Eduardo Matheus correia
Eduardo Milena Nóbrega Albuquerque
Eduardo Samuel Gomes
Eduardo Tayane Ysla Medeiros Gomes
Eduardo Washington Filho
Eduardo joão max nogueira de andrade
Eduardo thalita tayana dantas de sousa
Eduardo Ana Luisa Londres Gomes Lins
Eduardo Déborah Maria Coutinho Alves
Eduardo Elaine Andrielly Monteiro da Silva
Eduardo Giovana Costa Dias Lins
Eduardo Júlia Duarte Andrade Oliveira
Eduardo Laryssa Gonçalves Couras
Eduardo Letícia Leandra de Castro Cunha
Eduardo Luísa Sabino Florêncio
Eduardo Lívia França Tenório Pinheiro
Eduardo Maria Cecília Maranhão Ribeiro
Eduardo Maria Clara Campelo Galvão Rodrigues
Eduardo Maria Eduarda Nóbrega Honório de Assis
Eduardo Maria Eduarda de Souza Nery Nascimento
Eduardo Monise Carvalho Nascimento
Eduardo Sophia Medeiros Bueno
Eduardo Alexander Viana Fragoso Junior
Eduardo Ana Beatriz Souza Lira Carneiro da Cunha
Eduardo Catharina Louise A. de Oliveira
Eduardo Gabriela Cristina de Oliveira Gouveia
Eduardo Heyell Kevin
Eduardo João Victor Oliveira Estrela
Eduardo Laís Maria P. de Sousa
Eduardo Luiza Medeiros
Eduardo Tainá Martins Costa Ferreira Silva
Eduardo Beatriz Vilhena Camara Menezes
Eduardo Hanna Diniz
Eduardo Júlia Gonçalves Gadelha
Eduardo Mariana Mello de Farias
Eduardo Adrya Catharinne Santos Sousa da Silva
Eduardo Ana Luíza Gomes de Lacerda Quintans
Eduardo Camille Gabrielly Araújo Jucá
Eduardo Eduardo Paulo Queiroz Torres
Eduardo Francisco Gomes de Freitas Junior
Eduardo Giuliana Felipe da Silva
Eduardo Isadora Ferraz
Eduardo Julia Barros barbosa
Eduardo Larissa Vinesof
Eduardo Maria Clara Gomes de Lacerda Quintans e Magalhães
Eduardo Maria Clara Oliveira Nascimento
Eduardo Maria Eduarda Morais Candeia
Eduardo Mateus Gualberto
Eduardo Otto Nóbrega Hofmann
Eduardo Thayná Maria Tavares de Oliveira
Eduardo Carolina W.Q.F Evangelista
Eduardo Gabriela Arnaud Bandeira
Eduardo Karolina Azevedo Bringel
Eduardo Letícia Meira
Eduardo Letícia de Oliveira Barreto
Eduardo Maria Eduarda Franco Londres
Eduardo Maria Eduarda de Azevedo Galdino b s
Eduardo Maria Luísa Dantas Teixeira de Carvalho Rocha
Eduardo Maria Paula Braga
Eduardo Nicole Cavalcanti Pereira
Eduardo Raissa Nóbrega Cordeiro
Eduardo Thainá Maria Vieira de Andrade
Eduardo Ana Beatriz de Freitas Coutinho
Eduardo Beatriz d'Avila Lins Lacerda
Eduardo Clarissa Frazão
Eduardo Fernanda de Queiroz Albuquerque
Eduardo Gabriel Bandeira
Eduardo Gabriele Guerra
Eduardo Geórgia Campos Perdigão
Eduardo Gonzalo Alonso Medeiros Bueno
Eduardo Henrique Fialho Carneiro Braga Costa
Eduardo Luana de Sá Mendes
Eduardo Lucas toscano
Eduardo Luiz Henrique Cartaxo Fernandes
Eduardo Paula Fechine
Eduardo Rodrigo Carneiro Meira Lima
Eduardo Ana Carolina Correia Magalhaes
Eduardo Ana Flávia Cartaxo Moura Rodrigues de Aquino
Eduardo Letícia Andrade de Almeida
Eduardo Livia Beatriz Estrela De Oliveira
Eduardo Luana Toscano Pereira Henriques Ribeiro
Eduardo Marcela Vitória
Eduardo Maria Alice de Sena Morais
Eduardo Maria Beatriz de Melo Queiroz
Eduardo Maria Eduarda Souza Minéo
Eduardo Maria Luísa Mendes Abrantes
Eduardo Ana Luísa Vasconcelos
Eduardo Danillo Fernandes Lira Dias
Eduardo José Ricardo Brito Pereira Segundo
Eduardo Maria Eduarda Souza Malheiros Feliciano
Eduardo Pedro Henrique de Castro Pinto Almeida
Eduardo Pedro Machado Lago
Eduardo Raquel Nobrega do Nascimento
Eduardo Rodrigo Medeiros Delgado
Eduardo Sofia Leite de Araújo
Eduardo Arthur Pessoa Travassos Vinagre
Eduardo Carlos Alberto De Assis Madruga Filho
Eduardo Fernando Amorim Pontes Neto
Eduardo Giulia Lopes Carvalho
Eduardo Giulia Nóbrega Coutinho
Eduardo Herculano Galvão
Eduardo José Nidival de Queiróz Júnior
Eduardo Matheus Henrique Oliveira da Nóbrega
Eduardo Neto
Eduardo Samuel Lemos
Eduardo Victor Holmes trindade Rocha
Eduardo Yohanna Kalynna Santos Wanderley
Eduardo Alexia Sampaio Menezes
Eduardo Ivaldo Aurélio
Eduardo Julianna Ventura Pereira
Eduardo Lara Pereira
Eduardo Lucca Nuto França De Albuquerque
Eduardo Maria Fernanda Moura de Lima
Eduardo Maryanahdantas@hotmail.com
Eduardo Ana caroline Gomes de Miranda Linhares
Eduardo Bruno Chianca Heim Teotonio
Eduardo Carlos Henrique Rocha
Eduardo Gabriela Rocha Jorge
Eduardo Luana Maria Teixeira de Carvalho Pessoa de Souza
Eduardo Maria Fernanda Aguiar R Coutinho
Eduardo Nathan Marlon Ferreira Carreiro
Eduardo Sophia Adelino Xavier Pontes de Freitas
Fabiana Adriel Ribeiro
Fabiana Breno Alves Amorim
Fabiana Gabriel Almeida
Fabiana Ivinyn Pessoa Freire Soares
Fabiana Mariana Amorim
Fabiana Natália de Brito Lima
Fabiana Renan Vieira Costa
Fabiana Rivaldo Ferreira de Freitas Filho
Fabiana Alice de Oliveira Maia
Fabiana Ana Karenina Barreto Amorim Pessoa
Fabiana Anne Gabrielle de Sousa Diniz
Fabiana Beatriz Diniz
Fabiana Camilla Ellen Crispim de Felix Nobrega
Fabiana Camilla Queiroz Ferreira
Fabiana Gabriella Gomes Ferreira gadelha
Fabiana Manuella Freire
Fabiana Myllena Enmyly Ferreira de Almeida
Fabiana Rafaela Maria Ribera Gonçalves de Souza
Fabiana Vitória Gouveia Gomes
Fabiana maria eduarda sarmento lucena
Fabiana Anna Beatriz de S.Ayres
Fabiana Daniela Freitas
Fabiana João Manoel Medeiros Oliveira Di Lorenzo
Fabiana Maitê Maria de Souza Veras
Fabiana Maria Fernanda Rodrigues Gomes
Fabiana Maria Laura de Carvalho Pinto
Fabiana Rebeca Ferrer Cruz
Fabiana Ana Luísa Campos Porpino
Fabiana Antonio Inacio Pimentel Rodrigues de Lemos Filho
Fabiana Arthur Moreira Meirelles
Fabiana Caio robson gomes luna cruz
Fabiana Elio Ribeiro de Morais Filho
Fabiana Joao Paulo Rodrigues
Fabiana José Vicente Abrantes Gadelha Neto
Fabiana Maria Eduarda Sales Freire
Fabiana Matheus correia
Fabiana Milena Nóbrega Albuquerque
Fabiana Samuel Gomes
Fabiana Tayane Ysla Medeiros Gomes
Fabiana Washington Filho
Fabiana joão max nogueira de andrade
Fabiana thalita tayana dantas de sousa
Fabiana Ana Luisa Londres Gomes Lins
Fabiana Déborah Maria Coutinho Alves
Fabiana Elaine Andrielly Monteiro da Silva
Fabiana Giovana Costa Dias Lins
Fabiana Júlia Duarte Andrade Oliveira
Fabiana Laryssa Gonçalves Couras
Fabiana Letícia Leandra de Castro Cunha
Fabiana Luísa Sabino Florêncio
Fabiana Lívia França Tenório Pinheiro
Fabiana Maria Cecília Maranhão Ribeiro
Fabiana Maria Clara Campelo Galvão Rodrigues
Fabiana Maria Eduarda Nóbrega Honório de Assis
Fabiana Maria Eduarda de Souza Nery Nascimento
Fabiana Monise Carvalho Nascimento
Fabiana Sophia Medeiros Bueno
Fabiana Alexander Viana Fragoso Junior
Fabiana Ana Beatriz Souza Lira Carneiro da Cunha
Fabiana Catharina Louise A. de Oliveira
Fabiana Gabriela Cristina de Oliveira Gouveia
Fabiana Heyell Kevin
Fabiana João Victor Oliveira Estrela
Fabiana Laís Maria P. de Sousa
Fabiana Luiza Medeiros
Fabiana Tainá Martins Costa Ferreira Silva
Fabiana Beatriz Vilhena Camara Menezes
Fabiana Hanna Diniz
Fabiana Júlia Gonçalves Gadelha
Fabiana Mariana Mello de Farias
Fabiana Adrya Catharinne Santos Sousa da Silva
Fabiana Ana Luíza Gomes de Lacerda Quintans
Fabiana Camille Gabrielly Araújo Jucá
Fabiana Eduardo Paulo Queiroz Torres
Fabiana Francisco Gomes de Freitas Junior
Fabiana Giuliana Felipe da Silva
Fabiana Isadora Ferraz
Fabiana Julia Barros barbosa
Fabiana Larissa Vinesof
Fabiana Maria Clara Gomes de Lacerda Quintans e Magalhães
Fabiana Maria Clara Oliveira Nascimento
Fabiana Maria Eduarda Morais Candeia
Fabiana Mateus Gualberto
Fabiana Otto Nóbrega Hofmann
Fabiana Thayná Maria Tavares de Oliveira
Fabiana Carolina W.Q.F Evangelista
Fabiana Gabriela Arnaud Bandeira
Fabiana Karolina Azevedo Bringel
Fabiana Letícia Meira
Fabiana Letícia de Oliveira Barreto
Fabiana Maria Eduarda Franco Londres
Fabiana Maria Eduarda de Azevedo Galdino b s
Fabiana Maria Luísa Dantas Teixeira de Carvalho Rocha
Fabiana Maria Paula Braga
Fabiana Nicole Cavalcanti Pereira
Fabiana Raissa Nóbrega Cordeiro
Fabiana Thainá Maria Vieira de Andrade
Fabiana Ana Beatriz de Freitas Coutinho
Fabiana Beatriz d'Avila Lins Lacerda
Fabiana Clarissa Frazão
Fabiana Fernanda de Queiroz Albuquerque
Fabiana Gabriel Bandeira
Fabiana Gabriele Guerra
Fabiana Geórgia Campos Perdigão
Fabiana Gonzalo Alonso Medeiros Bueno
Fabiana Henrique Fialho Carneiro Braga Costa
Fabiana Luana de Sá Mendes
Fabiana Lucas toscano
Fabiana Luiz Henrique Cartaxo Fernandes
Fabiana Paula Fechine
Fabiana Rodrigo Carneiro Meira Lima
Fabiana Ana Carolina Correia Magalhaes
Fabiana Ana Flávia Cartaxo Moura Rodrigues de Aquino
Fabiana Letícia Andrade de Almeida
Fabiana Livia Beatriz Estrela De Oliveira
Fabiana Luana Toscano Pereira Henriques Ribeiro
Fabiana Marcela Vitória
Fabiana Maria Alice de Sena Morais
Fabiana Maria Beatriz de Melo Queiroz
Fabiana Maria Eduarda Souza Minéo
Fabiana Maria Luísa Mendes Abrantes
Fabiana Ana Luísa Vasconcelos
Fabiana Danillo Fernandes Lira Dias
Fabiana José Ricardo Brito Pereira Segundo
Fabiana Maria Eduarda Souza Malheiros Feliciano
Fabiana Pedro Henrique de Castro Pinto Almeida
Fabiana Pedro Machado Lago
Fabiana Raquel Nobrega do Nascimento
Fabiana Rodrigo Medeiros Delgado
Fabiana Sofia Leite de Araújo
Fabiana Arthur Pessoa Travassos Vinagre
Fabiana Carlos Alberto De Assis Madruga Filho
Fabiana Fernando Amorim Pontes Neto
Fabiana Giulia Lopes Carvalho
Fabiana Giulia Nóbrega Coutinho
Fabiana Herculano Galvão
Fabiana José Nidival de Queiróz Júnior
Fabiana Matheus Henrique Oliveira da Nóbrega
Fabiana Neto
Fabiana Samuel Lemos
Fabiana Victor Holmes trindade Rocha
Fabiana Yohanna Kalynna Santos Wanderley
Fabiana Alexia Sampaio Menezes
Fabiana Ivaldo Aurélio
Fabiana Julianna Ventura Pereira
Fabiana Lara Pereira
Fabiana Lucca Nuto França De Albuquerque
Fabiana Maria Fernanda Moura de Lima
Fabiana Maryanahdantas@hotmail.com
Fabiana Ana caroline Gomes de Miranda Linhares
Fabiana Bruno Chianca Heim Teotonio
Fabiana Carlos Henrique Rocha
Fabiana Gabriela Rocha Jorge
Fabiana Luana Maria Teixeira de Carvalho Pessoa de Souza
Fabiana Maria Fernanda Aguiar R Coutinho
Fabiana Nathan Marlon Ferreira Carreiro
Fabiana Sophia Adelino Xavier Pontes de Freitas

In [46]:
compatibility_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Breno Alves Amorim,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gabriel Almeida,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,-1
Ivinyn Pessoa Freire Soares,-1,0,-1,-1,-1,0,0,-1,0,-1,-1,-1,0,0,-1
Mariana Amorim,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Luana Maria Teixeira de Carvalho Pessoa de Souza,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Maria Fernanda Aguiar R Coutinho,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Nathan Marlon Ferreira Carreiro,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Sophia Adelino Xavier Pontes de Freitas,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

* Com isso conseguimos limitar a compatibilidade com os assessores

### Gender

* Here we will compare two columns, the gender and the answer to the question if the person feels comfortable with an advisor of the oposite sex

* Gender is 2 and the question is 32

In [47]:
df_students_answered[2].value_counts()/df_students_answered.shape[0] * 100 #percentage

Feminino     69.426752
Masculino    30.573248
Name: 2, dtype: float64

In [48]:
df_students_answered[32].value_counts()/df_students_answered.shape[0] * 100

Indiferente                   64.33121
sim, fico mais confortável    35.66879
Name: 32, dtype: float64

* 35.66% said they rather stay with an advisor of the same sex

In [49]:
from sklearn.preprocessing import LabelEncoder #we are using to keep it simple

In [50]:
le = LabelEncoder()
le.fit(df_students_answered[32])
print(le.classes_)

['Indiferente' 'sim, fico mais confortável']

In [51]:
df_students_answered[32] = le.transform(df_students_answered[32])

/home/itamar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [52]:
df_students_answered.head(3)

,0,Aluno,tempo,1,2,Quão compatível com seu assessor você se considera?,3,4,5,6,...,23,24,25,26,27,28,29,30,31,32
Aluno,,,,,,,,,,,,,,,,,,,,,
Adriel Ribeiro,Ariel,Adriel Ribeiro,3,18.0,Masculino,8.0,Motiva,Cristianismo,Sim,5.0,...,3.0,Não,Talvez,Aberto,Sim,Sim,Os dois,8.0,Procrastinação,1
Breno Alves Amorim,Ariel,Breno Alves Amorim,2,19.0,Masculino,10.0,Outro em João Pessoa,Cristianismo,Sim,3.0,...,7.0,Sim,Sim,Aberto,Sim,mais ou menos,Os dois,10.0,Procrastinação,0
Gabriel Almeida,Ariel,Gabriel Almeida,2,21.0,Masculino,10.0,Motiva,Cristianismo,Sim,5.0,...,6.0,Sim,Não,Aberto,Sim,mais ou menos,Estudos,8.0,Procrastinação,1

* We can see in column 32 that despite the warning, it works just fine.

In [53]:
# its clear that we could do all the iterations with the previous loop and some of the next ones, but our goal here
# is to make it more compreensive
for advisor in df_assessores[0]:
    advisor_sex = df_assessores.loc[advisor][2]
    for student in df_students_answered.Aluno:
        student_sex = df_students_answered.loc[student][2]
        student_preference = df_students_answered.loc[student][32]
        
        if student_sex != advisor_sex and student_preference:
            compatibility_matrix[advisor][student] = -1

In [54]:
compatibility_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,0,-1,-1,0,-1,0,-1,0,-1,0,-1,0,0,-1,0
Breno Alves Amorim,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gabriel Almeida,0,-1,-1,0,-1,0,-1,0,-1,0,-1,-1,0,-1,-1
Ivinyn Pessoa Freire Soares,-1,0,-1,-1,-1,0,0,-1,0,-1,-1,-1,0,0,-1
Mariana Amorim,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Luana Maria Teixeira de Carvalho Pessoa de Souza,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Maria Fernanda Aguiar R Coutinho,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Nathan Marlon Ferreira Carreiro,0,-1,-1,0,-1,0,-1,0,-1,0,-1,0,0,-1,0
Sophia Adelino Xavier Pontes de Freitas,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [55]:
del questions_dict[1]
del questions_dict[2]
del questions_dict[32]

### Examining the next and deleting columns
* Lets see

In [56]:
questions_dict

{0: 'Quem é você?',
 3: 'Onde fez ensino médio?',
 4: 'Alguma religião?',
 5: 'Gosta de esportes?',
 6: 'Como foi a qualidade de seu ensino médio?',
 7: 'Você se envolve com política?',
 8: 'Como se considera politicamente?',
 9: 'Que área compreende o curso que deseja fazer/faz na faculdade?',
 10: 'Qual sua área preferida no ENEM?',
 11: 'Quantos irmãos você tem?',
 12: 'Tem ou já teve algum problema de saúde físico?',
 13: 'Tem ou já teve algum problema de saúde mental?',
 14: 'tem experiência com vestibulares mais tradicionais e de outros estados?',
 15: 'Pratica atividade física com frequência?',
 16: 'Introvertido ou extrovertido?',
 17: 'No tempo livre prefere:',
 18: 'Tem facilidade em fazer amizades?',
 19: 'Que tipo de assessor você é?',
 20: 'Quantas vezes já fez enem? (sem contar como treineiro)',
 21: 'Você se considera uma pessoa paciente?',
 22: 'Você é organizado?',
 23: 'Quão sensível você é?',
 24: 'Você costuma cobrar seus alunos?',
 25: 'Você é competitivo?',
 26: 'Você é aberto a mudanças? ou é mais resistente?',
 27: 'Você costuma passar simulados pros alunos?',
 28: 'Você recebe apoio da sua família?',
 29: 'você costuma conversar com seus alunos sobre a vida pessoal deles ou só estudos?',
 30: 'Quão bom você é em motivar seus alunos?',
 31: 'Qual problema você é mais apto a ajudar os seus alunos a resolver?'}

In [57]:
df_assessores[29].value_counts() # all the same

Os dois    15
Name: 29, dtype: int64

In [58]:
del questions_dict[29]

## Non constraining questions

In [59]:
questions_dict

{0: 'Quem é você?',
 3: 'Onde fez ensino médio?',
 4: 'Alguma religião?',
 5: 'Gosta de esportes?',
 6: 'Como foi a qualidade de seu ensino médio?',
 7: 'Você se envolve com política?',
 8: 'Como se considera politicamente?',
 9: 'Que área compreende o curso que deseja fazer/faz na faculdade?',
 10: 'Qual sua área preferida no ENEM?',
 11: 'Quantos irmãos você tem?',
 12: 'Tem ou já teve algum problema de saúde físico?',
 13: 'Tem ou já teve algum problema de saúde mental?',
 14: 'tem experiência com vestibulares mais tradicionais e de outros estados?',
 15: 'Pratica atividade física com frequência?',
 16: 'Introvertido ou extrovertido?',
 17: 'No tempo livre prefere:',
 18: 'Tem facilidade em fazer amizades?',
 19: 'Que tipo de assessor você é?',
 20: 'Quantas vezes já fez enem? (sem contar como treineiro)',
 21: 'Você se considera uma pessoa paciente?',
 22: 'Você é organizado?',
 23: 'Quão sensível você é?',
 24: 'Você costuma cobrar seus alunos?',
 25: 'Você é competitivo?',
 26: 'Você é aberto a mudanças? ou é mais resistente?',
 27: 'Você costuma passar simulados pros alunos?',
 28: 'Você recebe apoio da sua família?',
 30: 'Quão bom você é em motivar seus alunos?',
 31: 'Qual problema você é mais apto a ajudar os seus alunos a resolver?'}

### Where completed high school or is studying

In [60]:
df_assessores[3].value_counts()

Motiva                       8
Outro em João Pessoa         3
Outra fora de João Pessoa    3
Geo                          1
Name: 3, dtype: int64

In [61]:
df_students_answered[3].value_counts()

Motiva                       65
Outro em João Pessoa         36
Outra fora de João Pessoa    23
Evolução                     20
Geo                           9
Cidade Viva                   4
Name: 3, dtype: int64

In [62]:
for advisor in df_assessores[0]:
    advisor_school = df_assessores.loc[advisor][3]
    for student in df_students_answered.Aluno:
        if compatibility_matrix[advisor][student] == -1:
            continue
        
        student_school = df_students_answered.loc[student][3]
        #print(advisor, student, student_school, advisor_school)
        if student_school == advisor_school:
            compatibility_matrix[advisor][student] = 1

In [63]:
compatibility_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,1,-1,-1,1,-1,1,-1,0,-1,1,-1,1,1,-1,0
Breno Alves Amorim,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0
Gabriel Almeida,1,-1,-1,1,-1,1,-1,0,-1,1,-1,-1,1,-1,-1
Ivinyn Pessoa Freire Soares,-1,0,-1,-1,-1,1,0,-1,0,-1,-1,-1,1,1,-1
Mariana Amorim,1,0,0,1,0,1,0,0,0,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0
Luana Maria Teixeira de Carvalho Pessoa de Souza,1,0,0,1,0,1,0,0,0,1,1,1,1,1,0
Maria Fernanda Aguiar R Coutinho,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Nathan Marlon Ferreira Carreiro,1,-1,-1,1,-1,1,-1,0,-1,1,-1,1,1,-1,0
Sophia Adelino Xavier Pontes de Freitas,1,0,0,1,0,1,0,0,0,1,1,1,1,1,0

In [64]:
del questions_dict[3]

### function to compute the rest

In [65]:
questions_dict

{0: 'Quem é você?',
 4: 'Alguma religião?',
 5: 'Gosta de esportes?',
 6: 'Como foi a qualidade de seu ensino médio?',
 7: 'Você se envolve com política?',
 8: 'Como se considera politicamente?',
 9: 'Que área compreende o curso que deseja fazer/faz na faculdade?',
 10: 'Qual sua área preferida no ENEM?',
 11: 'Quantos irmãos você tem?',
 12: 'Tem ou já teve algum problema de saúde físico?',
 13: 'Tem ou já teve algum problema de saúde mental?',
 14: 'tem experiência com vestibulares mais tradicionais e de outros estados?',
 15: 'Pratica atividade física com frequência?',
 16: 'Introvertido ou extrovertido?',
 17: 'No tempo livre prefere:',
 18: 'Tem facilidade em fazer amizades?',
 19: 'Que tipo de assessor você é?',
 20: 'Quantas vezes já fez enem? (sem contar como treineiro)',
 21: 'Você se considera uma pessoa paciente?',
 22: 'Você é organizado?',
 23: 'Quão sensível você é?',
 24: 'Você costuma cobrar seus alunos?',
 25: 'Você é competitivo?',
 26: 'Você é aberto a mudanças? ou é mais resistente?',
 27: 'Você costuma passar simulados pros alunos?',
 28: 'Você recebe apoio da sua família?',
 30: 'Quão bom você é em motivar seus alunos?',
 31: 'Qual problema você é mais apto a ajudar os seus alunos a resolver?'}

In [66]:
df_students_answered[24]

Aluno
Adriel Ribeiro                                         Não
Breno Alves Amorim                                     Sim
Gabriel Almeida                                        Sim
Ivinyn Pessoa Freire Soares                         Talvez
Mariana Amorim                                         Sim
                                                     ...
Gabriela Rocha Jorge                                Talvez
Luana Maria Teixeira de Carvalho Pessoa de Souza    Talvez
Maria Fernanda Aguiar R Coutinho                       Sim
Nathan Marlon Ferreira Carreiro                        Não
Sophia Adelino Xavier Pontes de Freitas                Sim
Name: 24, Length: 157, dtype: object

In [67]:
df_assessores[24]

0
Davi                 Sim
Lorenna              Sim
Rayssa               Sim
Débora               Sim
Glaucielle           Sim
Patriota          Talvez
Ariel                Sim
Rodrigo           Talvez
Carolzinha           Sim
Eduardo           Talvez
Mateus Tavares    Talvez
Fabiana           Talvez
Catharina            Sim
Itamar               Sim
Gelielison           Sim
Name: 24, dtype: object

In [68]:
def compute_compability(list_of_proportional, compatibility_matrix, df_assessores, df_students_answered):
    """
        args:
            list_of_proportional -> list with the columns that the function must act in
            
        return:
            compatibility matrix
    """
    for column in list_of_proportional:
        for advisor in df_assessores[0]:
            advisor_variable = df_assessores.loc[advisor][column]
            for student in df_students_answered.Aluno:
                if compatibility_matrix[advisor][student] == -1:
                    continue

                student_variable = df_students_answered.loc[student][column]
                #print(advisor, student, student_school, advisor_school)
                if advisor_variable == student_variable:
                    compatibility_matrix[advisor][student] += 1
    return compatibility_matrix

In [69]:
proportion_list = [4,5,8,9,10,12,13,14,15,17,19,24,25,27,28,31]
compute_compability(proportion_list, compatibility_matrix, df_assessores, df_students_answered)

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,8,-1,-1,11,-1,9,-1,10,-1,11,-1,9,10,-1,6
Breno Alves Amorim,8,8,6,9,10,6,8,9,11,10,10,10,9,8,7
Gabriel Almeida,8,-1,-1,11,-1,7,-1,10,-1,12,-1,-1,9,-1,-1
Ivinyn Pessoa Freire Soares,-1,7,-1,-1,-1,9,6,-1,10,-1,-1,-1,9,6,-1
Mariana Amorim,7,10,6,11,8,9,7,9,9,8,5,7,6,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,8,6,5,6,8,8,9,10,6,7,7,8,10,7,4
Luana Maria Teixeira de Carvalho Pessoa de Souza,8,8,9,7,9,11,10,7,8,8,8,8,9,7,7
Maria Fernanda Aguiar R Coutinho,9,10,7,6,9,8,4,11,10,7,10,5,8,7,7
Nathan Marlon Ferreira Carreiro,5,-1,-1,8,-1,6,-1,7,-1,7,-1,7,7,-1,6
Sophia Adelino Xavier Pontes de Freitas,10,7,7,7,8,8,6,6,6,8,9,9,7,7,5

In [70]:
for column in proportion_list:
    del questions_dict[column]

### More complex questions

In [71]:
questions_dict

{0: 'Quem é você?',
 6: 'Como foi a qualidade de seu ensino médio?',
 7: 'Você se envolve com política?',
 11: 'Quantos irmãos você tem?',
 16: 'Introvertido ou extrovertido?',
 18: 'Tem facilidade em fazer amizades?',
 20: 'Quantas vezes já fez enem? (sem contar como treineiro)',
 21: 'Você se considera uma pessoa paciente?',
 22: 'Você é organizado?',
 23: 'Quão sensível você é?',
 26: 'Você é aberto a mudanças? ou é mais resistente?',
 30: 'Quão bom você é em motivar seus alunos?'}

In [72]:
df_students_answered[6].value_counts()

4.0    70
3.0    47
5.0    28
2.0     9
0.0     2
1.0     1
Name: 6, dtype: int64

In [73]:
df_assessores[6].value_counts()

3    7
4    6
5    2
Name: 6, dtype: int64

In [74]:
# all the advisors are well prepared for their role, but their vivency, may be a factor that can influence
# the compatibility
for advisor in df_assessores[0]:
    advisor_hg_quality = df_assessores.loc[advisor][6]
    for student in df_students_answered.Aluno:
        if compatibility_matrix[advisor][student] == -1:
            continue
            
        student_hg_quality = df_students_answered.loc[student][6]

        if advisor_hg_quality + 2 >= student_hg_quality and advisor_hg_quality - 2 <= student_hg_quality:
            compatibility_matrix[advisor][student] += 1

In [75]:
compatibility_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,9,-1,-1,12,-1,10,-1,11,-1,12,-1,10,11,-1,7
Breno Alves Amorim,9,9,7,10,11,7,9,10,12,11,11,11,10,9,8
Gabriel Almeida,9,-1,-1,12,-1,8,-1,11,-1,13,-1,-1,10,-1,-1
Ivinyn Pessoa Freire Soares,-1,8,-1,-1,-1,10,7,-1,11,-1,-1,-1,10,7,-1
Mariana Amorim,8,11,7,12,9,10,8,10,10,9,6,8,7,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,9,7,6,7,9,9,10,11,7,8,8,9,11,8,5
Luana Maria Teixeira de Carvalho Pessoa de Souza,9,9,10,8,10,12,11,8,9,9,9,9,10,8,8
Maria Fernanda Aguiar R Coutinho,10,11,8,7,10,9,5,12,11,8,11,6,9,8,8
Nathan Marlon Ferreira Carreiro,6,-1,-1,8,-1,7,-1,8,-1,8,-1,8,8,-1,7
Sophia Adelino Xavier Pontes de Freitas,11,8,8,8,9,9,7,7,7,9,10,10,8,8,6

In [76]:
del questions_dict[6]

### next feature

In [77]:
questions_dict

{0: 'Quem é você?',
 7: 'Você se envolve com política?',
 11: 'Quantos irmãos você tem?',
 16: 'Introvertido ou extrovertido?',
 18: 'Tem facilidade em fazer amizades?',
 20: 'Quantas vezes já fez enem? (sem contar como treineiro)',
 21: 'Você se considera uma pessoa paciente?',
 22: 'Você é organizado?',
 23: 'Quão sensível você é?',
 26: 'Você é aberto a mudanças? ou é mais resistente?',
 30: 'Quão bom você é em motivar seus alunos?'}

In [78]:
df_students_answered[11] = df_students_answered[11].replace("6+",6)

/home/itamar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [79]:
df_students_answered[11].value_counts()

1    91
2    39
3    15
5     5
0     4
6     2
4     1
Name: 11, dtype: int64

In [80]:
df_assessores[11].value_counts()

2    5
1    4
0    4
5    1
3    1
Name: 11, dtype: int64

In [81]:
for advisor in df_assessores[0]:
    advisor_siblings = df_assessores.loc[advisor][11]
    advisor_attempts = df_assessores.loc[advisor][20]
    for student in df_students_answered.Aluno:
        if compatibility_matrix[advisor][student] == -1:
            continue
            
        student_siblings = int(df_students_answered.loc[student][11])
        student_attemps = df_students_answered.loc[student][20]

        if advisor_siblings > 1 and student_siblings > 1:
            compatibility_matrix[advisor][student] += 1
        elif advisor_siblings <= 1 and student_siblings <= 1:
            compatibility_matrix[advisor][student]
        
        if student_attemps >= 2 and advisor_attempts >= 2:
            compatibility_matrix[advisor][student] += 1
        elif student_attemps < 2 and advisor_attempts < 2:
            compatibility_matrix[advisor][student] += 1

In [82]:
compatibility_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,9,-1,-1,12,-1,11,-1,11,-1,12,-1,10,11,-1,7
Breno Alves Amorim,10,11,9,11,12,8,10,11,14,13,12,13,11,10,10
Gabriel Almeida,10,-1,-1,13,-1,9,-1,12,-1,15,-1,-1,11,-1,-1
Ivinyn Pessoa Freire Soares,-1,10,-1,-1,-1,11,8,-1,13,-1,-1,-1,11,8,-1
Mariana Amorim,9,12,8,13,10,10,9,11,11,10,7,9,8,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,9,8,7,7,9,11,10,11,8,9,8,10,11,8,6
Luana Maria Teixeira de Carvalho Pessoa de Souza,10,10,11,9,11,12,12,9,10,10,10,10,11,9,9
Maria Fernanda Aguiar R Coutinho,10,12,9,7,10,11,5,12,12,9,11,7,9,8,9
Nathan Marlon Ferreira Carreiro,7,-1,-1,9,-1,8,-1,9,-1,10,-1,10,9,-1,9
Sophia Adelino Xavier Pontes de Freitas,11,8,8,8,9,10,7,7,7,9,10,10,8,8,6

In [83]:
del questions_dict[11]

In [84]:
del questions_dict[20]

In [85]:
del questions_dict[7]

In [86]:
del questions_dict[0]

### Checando o que seriam as penalidades

In [87]:
questions_dict

{16: 'Introvertido ou extrovertido?',
 18: 'Tem facilidade em fazer amizades?',
 21: 'Você se considera uma pessoa paciente?',
 22: 'Você é organizado?',
 23: 'Quão sensível você é?',
 26: 'Você é aberto a mudanças? ou é mais resistente?',
 30: 'Quão bom você é em motivar seus alunos?'}

#### introverção

In [88]:
df_students_answered[16].value_counts()

Meio termo      82
Extrovertido    52
Introvertido    23
Name: 16, dtype: int64

In [89]:
df_assessores[16].value_counts()

Extrovertido    7
Meio termo      7
Introvertido    1
Name: 16, dtype: int64

In [90]:
df_assessores[16] = df_assessores[16].replace("Meio termo","meio termo")

In [91]:
df_students_answered[16] = df_students_answered[16].replace("Meio termo", "meio termo")

/home/itamar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

#### Amizades

In [92]:
df_students_answered[18].value_counts()

meio termo    77
sim           67
Não           13
Name: 18, dtype: int64

In [93]:
df_assessores[18].value_counts()

sim           8
meio termo    7
Name: 18, dtype: int64

#### Paciência

In [94]:
df_students_answered[21].value_counts()

meio termo    63
Sim           55
Não           39
Name: 21, dtype: int64

In [95]:
df_assessores[21].value_counts()

Sim           11
meio termo     4
Name: 21, dtype: int64

#### Organização

In [96]:
df_students_answered[22].value_counts()

Sim    113
Não     44
Name: 22, dtype: int64

In [97]:
df_assessores[22].value_counts()

Sim    12
Não     3
Name: 22, dtype: int64

#### Sensível

In [98]:
df_students_answered[23].value_counts()

8.0     35
7.0     31
9.0     24
5.0     18
10.0    17
6.0     16
4.0      9
3.0      5
2.0      2
Name: 23, dtype: int64

In [99]:
df_assessores[23].value_counts()

8    7
7    3
9    1
6    1
5    1
4    1
3    1
Name: 23, dtype: int64

### Mudanças

In [100]:
df_students_answered[26].value_counts()

Aberto        117
Resistente     40
Name: 26, dtype: int64

In [101]:
df_assessores[26].value_counts()

Aberto    15
Name: 26, dtype: int64

* é inútil porque ta tudo igual dos assessores

In [102]:
del questions_dict[26]

#### Motivação

In [103]:
df_students_answered[30].value_counts()

8.0     40
7.0     37
6.0     26
9.0     18
5.0     15
10.0    10
4.0      8
3.0      3
Name: 30, dtype: int64

In [104]:
df_assessores[30]

0
Davi               8
Lorenna            9
Rayssa             5
Débora             7
Glaucielle         9
Patriota           8
Ariel             10
Rodrigo            7
Carolzinha         9
Eduardo            9
Mateus Tavares     8
Fabiana            9
Catharina          9
Itamar             9
Gelielison         8
Name: 30, dtype: int64

### adicionando as bonificações das variáveis acima

In [105]:
questions_dict

{16: 'Introvertido ou extrovertido?',
 18: 'Tem facilidade em fazer amizades?',
 21: 'Você se considera uma pessoa paciente?',
 22: 'Você é organizado?',
 23: 'Quão sensível você é?',
 30: 'Quão bom você é em motivar seus alunos?'}

In [106]:
def compute_compatibility_reverse(list_of_columns, compat_matrix, df_assessores, df_students_answered):
    for column in list_of_columns:
        for advisor in df_assessores[0]:
            advisor_var = df_assessores.loc[advisor][column]
            
            for student in df_students_answered.Aluno:
                if compatibility_matrix[advisor][student] == -1:
                    continue
                student_var = df_students_answered.loc[student][column]
                
                if student_var == "meio termo":
                    compat_matrix[advisor][student] += 1
                elif student_var != "meio termo" and advisor_var != "meio termo" and advisor_var != student_var:
                    compat_matrix[advisor][student] += 1
    
    return compat_matrix

In [107]:
compatibility_matrix = compute_compatibility_reverse([16,18,21,22], compatibility_matrix.copy() ,df_assessores, df_students_answered)

In [108]:
compatibility_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,11,-1,-1,14,-1,13,-1,13,-1,15,-1,13,13,-1,10
Breno Alves Amorim,12,13,10,13,14,10,12,13,16,15,14,14,13,12,11
Gabriel Almeida,14,-1,-1,17,-1,13,-1,16,-1,19,-1,-1,15,-1,-1
Ivinyn Pessoa Freire Soares,-1,13,-1,-1,-1,14,11,-1,16,-1,-1,-1,14,11,-1
Mariana Amorim,12,15,10,16,13,13,12,14,14,13,10,11,11,11,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,12,11,9,10,12,14,13,14,11,12,11,12,14,11,8
Luana Maria Teixeira de Carvalho Pessoa de Souza,11,10,13,10,11,13,12,10,11,12,11,12,11,10,11
Maria Fernanda Aguiar R Coutinho,14,15,12,11,13,15,8,16,16,13,15,10,12,12,12
Nathan Marlon Ferreira Carreiro,10,-1,-1,12,-1,11,-1,12,-1,13,-1,12,12,-1,11
Sophia Adelino Xavier Pontes de Freitas,14,11,12,10,10,12,8,10,10,10,12,12,11,9,8

In [109]:
df_students_answered[[16,18,21,22]].head(1)

                          16          18          21   22
Aluno
Adriel Ribeiro  Extrovertido  meio termo  meio termo  Sim

In [110]:
df_assessores.loc["Itamar"][[16,18,21,22]]

16    Introvertido
18      meio termo
21             Sim
22             Sim
Name: Itamar, dtype: object

In [111]:
del questions_dict[16]
del questions_dict[18]
del questions_dict[21]

In [112]:
del questions_dict[22]

In [113]:
questions_dict

{23: 'Quão sensível você é?', 30: 'Quão bom você é em motivar seus alunos?'}

### last two variables

In [114]:
for advisor in df_assessores[0]:
    advisor_sensibility = int(df_assessores.loc[advisor][23])
    
    for student in df_students_answered.Aluno:
        
        if compatibility_matrix[advisor][student] == -1:
            continue
    
        student_sensibility = int(df_students_answered.loc[student][23])

        if student_sensibility > 7 and advisor_sensibility > 7:
            compatibility_matrix[advisor][student] += 1
        elif student_sensibility < 7 and advisor_sensibility < 7:
            compatibility_matrix[advisor][student] += 1

In [115]:
compatibility_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,11,-1,-1,15,-1,13,-1,13,-1,16,-1,13,13,-1,10
Breno Alves Amorim,12,13,10,13,14,10,12,13,16,15,14,14,13,12,11
Gabriel Almeida,14,-1,-1,18,-1,13,-1,16,-1,20,-1,-1,15,-1,-1
Ivinyn Pessoa Freire Soares,-1,14,-1,-1,-1,14,12,-1,17,-1,-1,-1,15,11,-1
Mariana Amorim,12,16,11,16,13,13,13,15,15,13,10,12,12,11,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,12,11,9,11,13,14,13,14,11,13,11,12,14,12,8
Luana Maria Teixeira de Carvalho Pessoa de Souza,11,10,13,10,11,13,12,10,11,12,11,12,11,10,11
Maria Fernanda Aguiar R Coutinho,14,16,13,11,13,15,9,17,17,13,15,11,13,12,13
Nathan Marlon Ferreira Carreiro,10,-1,-1,12,-1,11,-1,13,-1,13,-1,13,13,-1,12
Sophia Adelino Xavier Pontes de Freitas,14,11,12,10,10,12,8,10,10,10,12,12,11,9,8

In [116]:
df_assessores[30].value_counts()

9     7
8     4
7     2
10    1
5     1
Name: 30, dtype: int64

In [117]:
df_students_answered[30].value_counts()

8.0     40
7.0     37
6.0     26
9.0     18
5.0     15
10.0    10
4.0      8
3.0      3
Name: 30, dtype: int64

In [118]:
for advisor in df_assessores[0]:
    advisor_motivation = int(df_assessores.loc[advisor][30])
    
    for student in df_students_answered.Aluno:
        
        if compatibility_matrix[advisor][student] == -1:
            continue
    
        student_motivation = int(df_students_answered.loc[student][30])

        if student_sensibility < 7 and advisor_sensibility > 8.5:
            compatibility_matrix[advisor][student] += 1
        elif student_sensibility > 7 and advisor_sensibility < 8.5:
            compatibility_matrix[advisor][student] += 1

In [119]:
compatibility_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,11,-1,-1,15,-1,13,-1,13,-1,16,-1,13,13,-1,10
Breno Alves Amorim,12,13,10,13,14,10,12,13,16,15,14,14,13,12,11
Gabriel Almeida,14,-1,-1,18,-1,13,-1,16,-1,20,-1,-1,15,-1,-1
Ivinyn Pessoa Freire Soares,-1,14,-1,-1,-1,14,12,-1,17,-1,-1,-1,15,11,-1
Mariana Amorim,12,16,11,16,13,13,13,15,15,13,10,12,12,11,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,12,11,9,11,13,14,13,14,11,13,11,12,14,12,8
Luana Maria Teixeira de Carvalho Pessoa de Souza,11,10,13,10,11,13,12,10,11,12,11,12,11,10,11
Maria Fernanda Aguiar R Coutinho,14,16,13,11,13,15,9,17,17,13,15,11,13,12,13
Nathan Marlon Ferreira Carreiro,10,-1,-1,12,-1,11,-1,13,-1,13,-1,13,13,-1,12
Sophia Adelino Xavier Pontes de Freitas,14,11,12,10,10,12,8,10,10,10,12,12,11,9,8

In [120]:
final_matrix = compatibility_matrix.replace(-1,-10000)

In [121]:
final_matrix

,Ariel,Carolzinha,Catharina,Davi,Débora,Eduardo,Fabiana,Gelielison,Glaucielle,Itamar,Lorenna,Mateus Tavares,Patriota,Rayssa,Rodrigo
Aluno,,,,,,,,,,,,,,,
Adriel Ribeiro,11,-10000,-10000,15,-10000,13,-10000,13,-10000,16,-10000,13,13,-10000,10
Breno Alves Amorim,12,13,10,13,14,10,12,13,16,15,14,14,13,12,11
Gabriel Almeida,14,-10000,-10000,18,-10000,13,-10000,16,-10000,20,-10000,-10000,15,-10000,-10000
Ivinyn Pessoa Freire Soares,-10000,14,-10000,-10000,-10000,14,12,-10000,17,-10000,-10000,-10000,15,11,-10000
Mariana Amorim,12,16,11,16,13,13,13,15,15,13,10,12,12,11,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gabriela Rocha Jorge,12,11,9,11,13,14,13,14,11,13,11,12,14,12,8
Luana Maria Teixeira de Carvalho Pessoa de Souza,11,10,13,10,11,13,12,10,11,12,11,12,11,10,11
Maria Fernanda Aguiar R Coutinho,14,16,13,11,13,15,9,17,17,13,15,11,13,12,13
Nathan Marlon Ferreira Carreiro,10,-10000,-10000,12,-10000,11,-10000,13,-10000,13,-10000,13,13,-10000,12
Sophia Adelino Xavier Pontes de Freitas,14,11,12,10,10,12,8,10,10,10,12,12,11,9,8

In [122]:
final_matrix["Ariel"]["Maria Eduarda Sales Freire"] = -10000

In [123]:
final_matrix["Itamar"]["Samuel Gomes"] = -10000

In [124]:
folder = 'data_preprocessed_and_compatibility'

In [125]:
pd.DataFrame(final_matrix.values).to_csv(f"{folder}/final_matrix.csv", header = False, index = False)

In [126]:
indexes = compatibility_matrix.index.values

In [127]:
indexes

array(['Adriel Ribeiro', 'Breno Alves Amorim', 'Gabriel Almeida',
       'Ivinyn Pessoa Freire Soares', 'Mariana Amorim',
       'Natália de Brito Lima', 'Renan Vieira Costa',
       'Rivaldo Ferreira de Freitas Filho', 'Alice de Oliveira Maia',
       'Ana Karenina Barreto Amorim Pessoa',
       'Anne Gabrielle de Sousa Diniz', 'Beatriz Diniz',
       'Camilla Ellen Crispim de Felix Nobrega',
       'Camilla Queiroz Ferreira', 'Gabriella Gomes Ferreira gadelha',
       'Manuella Freire', 'Myllena Enmyly Ferreira de Almeida',
       'Rafaela Maria Ribera Gonçalves de Souza', 'Vitória Gouveia Gomes',
       'maria eduarda sarmento lucena', 'Anna Beatriz de S.Ayres',
       'Daniela Freitas', 'João Manoel Medeiros Oliveira Di Lorenzo',
       'Maitê Maria de Souza Veras', 'Maria Fernanda Rodrigues Gomes',
       'Maria Laura de Carvalho Pinto', 'Rebeca Ferrer Cruz',
       'Ana Luísa Campos Porpino',
       'Antonio Inacio Pimentel Rodrigues de Lemos Filho',
       'Arthur Moreira Meirelles', 'Caio robson gomes luna cruz',
       'Elio Ribeiro de Morais Filho', 'Joao Paulo Rodrigues',
       'José Vicente Abrantes Gadelha Neto', 'Maria Eduarda Sales Freire',
       'Matheus correia', 'Milena Nóbrega Albuquerque', 'Samuel Gomes',
       'Tayane Ysla Medeiros Gomes', 'Washington Filho',
       'joão max nogueira de andrade', 'thalita tayana dantas de sousa',
       'Ana Luisa Londres Gomes Lins', 'Déborah Maria Coutinho Alves',
       'Elaine Andrielly Monteiro da Silva', 'Giovana Costa Dias Lins',
       'Júlia Duarte Andrade Oliveira', 'Laryssa Gonçalves Couras',
       'Letícia Leandra de Castro Cunha', 'Luísa Sabino Florêncio',
       'Lívia França Tenório Pinheiro', 'Maria Cecília Maranhão Ribeiro',
       'Maria Clara Campelo Galvão Rodrigues',
       'Maria Eduarda Nóbrega Honório de Assis',
       'Maria Eduarda de Souza Nery Nascimento',
       'Monise Carvalho Nascimento', 'Sophia Medeiros Bueno',
       'Alexander Viana Fragoso Junior',
       'Ana Beatriz Souza Lira Carneiro da Cunha',
       'Catharina Louise A. de Oliveira',
       'Gabriela Cristina de Oliveira Gouveia', 'Heyell Kevin',
       'João Victor Oliveira Estrela', 'Laís Maria P. de Sousa',
       'Luiza Medeiros', 'Tainá Martins Costa Ferreira Silva',
       'Beatriz Vilhena Camara Menezes', 'Hanna Diniz',
       'Júlia Gonçalves Gadelha', 'Mariana Mello de Farias',
       'Adrya Catharinne Santos Sousa da Silva',
       'Ana Luíza Gomes de Lacerda Quintans',
       'Camille Gabrielly Araújo Jucá', 'Eduardo Paulo Queiroz Torres',
       'Francisco Gomes de Freitas Junior', 'Giuliana Felipe da Silva',
       'Isadora Ferraz', 'Julia Barros barbosa', 'Larissa Vinesof',
       'Maria Clara Gomes de Lacerda Quintans e Magalhães',
       'Maria Clara Oliveira Nascimento', 'Maria Eduarda Morais Candeia',
       'Mateus Gualberto', 'Otto Nóbrega Hofmann',
       'Thayná Maria Tavares de Oliveira', 'Carolina W.Q.F Evangelista',
       'Gabriela Arnaud Bandeira', 'Karolina Azevedo Bringel',
       'Letícia Meira', 'Letícia de Oliveira Barreto',
       'Maria Eduarda Franco Londres',
       'Maria Eduarda de Azevedo Galdino b s',
       'Maria Luísa Dantas Teixeira de Carvalho Rocha',
       'Maria Paula Braga', 'Nicole Cavalcanti Pereira',
       'Raissa Nóbrega Cordeiro', 'Thainá Maria Vieira de Andrade',
       'Ana Beatriz de Freitas Coutinho', "Beatriz d'Avila Lins Lacerda",
       'Clarissa Frazão', 'Fernanda de Queiroz Albuquerque',
       'Gabriel Bandeira', 'Gabriele Guerra', 'Geórgia Campos Perdigão',
       'Gonzalo Alonso Medeiros Bueno',
       'Henrique Fialho Carneiro Braga Costa', 'Luana de Sá Mendes',
       'Lucas toscano', 'Luiz Henrique Cartaxo Fernandes',
       'Paula Fechine', 'Rodrigo Carneiro Meira Lima',
       'Ana Carolina Correia Magalhaes',
       'Ana Flávia Cartaxo Moura Rodrigues de Aquino',
       'Letícia Andrade de Almeida', 'Livia Beatriz Estrela De Oliveira',
       'Luana Toscano Pereira Henriques Ribeiro', 'Marcela Vitória',
       'Maria Alice de Sena Morais', 'Maria Beatriz de Melo Queiroz',
       'Maria Eduarda Souza Minéo', 'Maria Luísa Mendes Abrantes',
       'Ana Luísa Vasconcelos', 'Danillo Fernandes Lira Dias',
       'José Ricardo Brito Pereira Segundo',
       'Maria Eduarda Souza Malheiros Feliciano',
       'Pedro Henrique de Castro Pinto Almeida', 'Pedro Machado Lago',
       'Raquel Nobrega do Nascimento', 'Rodrigo Medeiros Delgado',
       'Sofia Leite de Araújo', 'Arthur Pessoa Travassos Vinagre',
       'Carlos Alberto De Assis Madruga Filho',
       'Fernando Amorim Pontes Neto', 'Giulia Lopes Carvalho',
       'Giulia Nóbrega Coutinho', 'Herculano Galvão',
       'José Nidival de Queiróz Júnior',
       'Matheus Henrique Oliveira da Nóbrega', 'Neto', 'Samuel Lemos',
       'Victor Holmes trindade Rocha', 'Yohanna Kalynna Santos Wanderley',
       'Alexia Sampaio Menezes', 'Ivaldo Aurélio',
       'Julianna Ventura Pereira', 'Lara Pereira',
       'Lucca Nuto França De Albuquerque', 'Maria Fernanda Moura de Lima',
       'Maryanahdantas@hotmail.com',
       'Ana caroline Gomes de Miranda Linhares',
       'Bruno Chianca Heim Teotonio', 'Carlos Henrique Rocha',
       'Gabriela Rocha Jorge',
       'Luana Maria Teixeira de Carvalho Pessoa de Souza',
       'Maria Fernanda Aguiar R Coutinho',
       'Nathan Marlon Ferreira Carreiro',
       'Sophia Adelino Xavier Pontes de Freitas'], dtype=object)

In [128]:
columns = compatibility_matrix.columns.values
columns

array(['Ariel', 'Carolzinha', 'Catharina', 'Davi', 'Débora', 'Eduardo',
       'Fabiana', 'Gelielison', 'Glaucielle', 'Itamar', 'Lorenna',
       'Mateus Tavares', 'Patriota', 'Rayssa', 'Rodrigo'], dtype=object)

In [129]:
pd.DataFrame(indexes).to_csv(f"{folder}/rows.csv", header = False, index = False)

In [130]:
pd.DataFrame(columns).to_csv(f"{folder}/columns.csv", header = False, index = False)

In [131]:
pd.DataFrame(df_students_answered.tempo.values).to_csv(f"{folder}/work_degree.csv", header = False, index = False)

### Getting the sum of the work of students that didnt answered the survey

In [132]:
df_students_notAnswered.head(1)

,Assessor,Aluno,tempo,Idade,Gênero,Quão compatível com seu assessor você se considera?,Onde fez/faz ensino médio?,Alguma religião?,Gosta de esportes?,Como foi/está sendo a qualidade de seu ensino médio?,...,Quão sensível você é?,Você gosta de ser cobrado?,Você é competitivo?,Você é aberto a mudanças? ou é mais resistente?,Você gosta de fazer simulado?,Você recebe apoio da sua família?,Você gostaria de falar sobre a vida pessoal com o assessor ou só estudos?,Quão motivado você está?,Qual é seu maior problema?,Você prefere um assessor do mesmo sexo?
1,Ariel,Alyce Dantas,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
fixed_students_table = df_students_notAnswered

In [134]:
df_students_notAnswered = df_students_notAnswered.dropna(how = "all", axis = 1)

In [135]:
df_students_notAnswered.head(1)

  Assessor         Aluno  tempo
1    Ariel  Alyce Dantas      4

In [136]:
df_students_notAnswered = df_students_notAnswered.drop("Aluno",axis = 1)

In [137]:
grouped = df_students_notAnswered.groupby("Assessor")

In [138]:
tempo = grouped.sum().tempo

In [139]:
tempo

Assessor
Ariel             21
Carolzinha        12
Catharina         38
Eduardo           27
Fabiana           33
Gelielison         4
Glaucielle         5
Lorenna           12
Mateus Tavares    19
Patriota          18
Rayssa            10
Rodrigo           28
Name: tempo, dtype: int64

In [140]:
students_already_computed = df_students_notAnswered.Assessor.value_counts()
students_already_computed

Fabiana           9
Catharina         8
Eduardo           7
Ariel             7
Rodrigo           7
Mateus Tavares    6
Rayssa            5
Lorenna           4
Patriota          4
Carolzinha        3
Glaucielle        1
Gelielison        1
Name: Assessor, dtype: int64

In [141]:
fixed_students = pd.DataFrame(students_already_computed).join(tempo).reset_index().sort_values(by = "index")

In [142]:
fixed_students

             index  Assessor  tempo
3            Ariel         7     21
9       Carolzinha         3     12
1        Catharina         8     38
2          Eduardo         7     27
0          Fabiana         9     33
11      Gelielison         1      4
10      Glaucielle         1      5
7          Lorenna         4     12
5   Mateus Tavares         6     19
8         Patriota         4     18
6           Rayssa         5     10
4          Rodrigo         7     28

In [143]:
fixed_students.shape

(12, 3)

* We only have 12 advisors here, we must add the ones that got all students ok (Davi, Itamar, Débora)

In [144]:
missing_advisors = pd.DataFrame([["Itamar", 0, 0],["Débora", 0, 0],["Davi", 0, 0]], columns = fixed_students.columns)

In [145]:
fixed_students = fixed_students.append(missing_advisors).sort_values(by = "index").reset_index(drop = True)

In [146]:
fixed_students

             index  Assessor  tempo
0            Ariel         7     21
1       Carolzinha         3     12
2        Catharina         8     38
3             Davi         0      0
4           Débora         0      0
5          Eduardo         7     27
6          Fabiana         9     33
7       Gelielison         1      4
8       Glaucielle         1      5
9           Itamar         0      0
10         Lorenna         4     12
11  Mateus Tavares         6     19
12        Patriota         4     18
13          Rayssa         5     10
14         Rodrigo         7     28

In [147]:
fixed_effort = pd.DataFrame(fixed_students.iloc[:,1:3].values)
fixed_effort

    0   1
0   7  21
1   3  12
2   8  38
3   0   0
4   0   0
5   7  27
6   9  33
7   1   4
8   1   5
9   0   0
10  4  12
11  6  19
12  4  18
13  5  10
14  7  28

In [148]:
fixed_effort.to_csv(f"{folder}/fixed_effort.csv", header=False, index = False)

* We sorted it so we dont need to worry about the names when using in the C++ file to optimize

### Making work effort "equal"

In [149]:
df.shape

(219, 36)

In [150]:
df_assessores.shape

(15, 33)

In [151]:
students_per_advisor = df.shape[0]/df_assessores.shape[0]
students_per_advisor

14.6

* The students for each may stay between 14 and 15

### Measuring effort

In [152]:
df.tempo.sum()/df_assessores.shape[0]

59.93333333333333

* The mean effort per advisor is 59.93, we will try to bound it to be less than 61 and bigger than 59.

# Final results

In [164]:
fixed_students = fixed_students_table.dropna(axis = 1).reset_index(drop = True)
fixed_students

   Assessor                  Aluno  tempo
0     Ariel           Alyce Dantas      4
1     Ariel        Barbara Camargo      2
2     Ariel             Caio Paiva      3
3     Ariel       Guilherme Varela      3
4     Ariel          Herbert Sodré      3
..      ...                    ...    ...
57  Rodrigo          Leticia Costa      3
58  Rodrigo  Maria Fernanda Burity      5
59  Rodrigo   Rita de Cassia Cunha      5
60  Rodrigo          Rodrigo Moura      2
61  Rodrigo        Vitória Beatriz      3

[62 rows x 3 columns]

In [210]:
students_allocated = pd.read_csv("result.csv", header = None)
students_allocated.columns = ["Assessor","Aluno","tempo"]
students_allocated

    Assessor                                              Aluno  tempo
0      Ariel                                 Renan Vieira Costa      5
1      Ariel                                      Beatriz Diniz      5
2      Ariel                       Elio Ribeiro de Morais Filho      5
3      Ariel                     thalita tayana dantas de sousa      5
4      Ariel  Maria Clara Gomes de Lacerda Quintans e Magalhães      5
..       ...                                                ...    ...
152  Rodrigo                             Luísa Sabino Florêncio      5
153  Rodrigo                           Giuliana Felipe da Silva      5
154  Rodrigo                   Thayná Maria Tavares de Oliveira      4
155  Rodrigo                                               Neto      4
156  Rodrigo                                     Ivaldo Aurélio      2

[157 rows x 3 columns]

In [211]:
resulting = students_allocated.append(fixed_students).reset_index(drop = True)
resulting

    Assessor                                              Aluno  tempo
0      Ariel                                 Renan Vieira Costa      5
1      Ariel                                      Beatriz Diniz      5
2      Ariel                       Elio Ribeiro de Morais Filho      5
3      Ariel                     thalita tayana dantas de sousa      5
4      Ariel  Maria Clara Gomes de Lacerda Quintans e Magalhães      5
..       ...                                                ...    ...
214  Rodrigo                                      Leticia Costa      3
215  Rodrigo                              Maria Fernanda Burity      5
216  Rodrigo                               Rita de Cassia Cunha      5
217  Rodrigo                                      Rodrigo Moura      2
218  Rodrigo                                    Vitória Beatriz      3

[219 rows x 3 columns]

In [212]:
previous_allocation = df.dropna(axis = 1)
previous_allocation

    Assessor                                    Aluno  tempo
0      Ariel                           Adriel Ribeiro      3
1      Ariel                             Alyce Dantas      4
2      Ariel                          Barbara Camargo      2
3      Ariel                       Breno Alves Amorim      2
4      Ariel                               Caio Paiva      3
..       ...                                      ...    ...
214  Rodrigo          Nathan Marlon Ferreira Carreiro      4
215  Rodrigo                     Rita de Cassia Cunha      5
216  Rodrigo                            Rodrigo Moura      2
217  Rodrigo  Sophia Adelino Xavier Pontes de Freitas      4
218  Rodrigo                          Vitória Beatriz      3

[219 rows x 3 columns]

## NEW RESULTS

### TIME

In [213]:
new_time = resulting.groupby("Assessor").sum().tempo
new_time

Assessor
Ariel             59
Carolzinha        60
Catharina         60
Davi              59
Débora            60
Eduardo           60
Fabiana           59
Gelielison        61
Glaucielle        61
Itamar            60
Lorenna           60
Mateus Tavares    61
Patriota          59
Rayssa            59
Rodrigo           61
Name: tempo, dtype: int64

In [214]:
previous_time = previous_allocation.groupby("Assessor").sum().tempo
previous_time

Assessor
Ariel             51
Carolzinha        67
Catharina         72
Davi              67
Débora            67
Eduardo           65
Fabiana           48
Gelielison        73
Glaucielle        64
Itamar            50
Lorenna           57
Mateus Tavares    61
Patriota          70
Rayssa            29
Rodrigo           58
Name: tempo, dtype: int64

* We now have a more uniform distribution

In [240]:
print(previous_time.std())
print(new_time.std())

11.65250841582843
0.7988086367179803

### Number of students

In [216]:
new_number = resulting.Assessor.value_counts()
new_number

Mateus Tavares    15
Glaucielle        15
Ariel             15
Rodrigo           15
Gelielison        15
Fabiana           15
Itamar            15
Rayssa            15
Lorenna           15
Eduardo           14
Davi              14
Catharina         14
Débora            14
Carolzinha        14
Patriota          14
Name: Assessor, dtype: int64

In [217]:
previous_number = previous_allocation.Assessor.value_counts()
previous_number

Eduardo           16
Gelielison        16
Patriota          16
Davi              15
Catharina         15
Mateus Tavares    15
Ariel             15
Débora            15
Rodrigo           15
Carolzinha        15
Itamar            14
Lorenna           14
Glaucielle        13
Fabiana           13
Rayssa            12
Name: Assessor, dtype: int64

In [218]:
print(previous_number.std())
print(new_number.std())

1.1832159566199232
0.50709255283711

* Another drastic reduction in the distribution

## Finalizing

In [219]:
resulting.head()

  Assessor                                              Aluno  tempo
0    Ariel                                 Renan Vieira Costa      5
1    Ariel                                      Beatriz Diniz      5
2    Ariel                       Elio Ribeiro de Morais Filho      5
3    Ariel                     thalita tayana dantas de sousa      5
4    Ariel  Maria Clara Gomes de Lacerda Quintans e Magalhães      5

In [220]:
previous_allocation.head()

  Assessor               Aluno  tempo
0    Ariel      Adriel Ribeiro      3
1    Ariel        Alyce Dantas      4
2    Ariel     Barbara Camargo      2
3    Ariel  Breno Alves Amorim      2
4    Ariel          Caio Paiva      3

In [223]:
resulting["previous_advisor"] = resulting.Assessor

In [224]:
resulting.head()

,Assessor,Aluno,tempo,previous_advisor
0,Ariel,Renan Vieira Costa,5,Ariel
1,Ariel,Beatriz Diniz,5,Ariel
2,Ariel,Elio Ribeiro de Morais Filho,5,Ariel
3,Ariel,thalita tayana dantas de sousa,5,Ariel
4,Ariel,Maria Clara Gomes de Lacerda Quintans e Magalhães,5,Ariel

In [232]:
previous_advisor = []
for index in resulting.index:
    aluno = resulting.loc[index]["Aluno"]
    reference_of_previous_alloc = previous_allocation.loc[previous_allocation.Aluno == aluno].index
    #print(previous_allocation.loc[reference_of_previous_alloc].Assessor.values[0])
    previous_advisor.append(previous_allocation.loc[reference_of_previous_alloc].Assessor.values[0])

In [233]:
resulting.previous_advisor = previous_advisor

In [234]:
resulting

,Assessor,Aluno,tempo,previous_advisor
0,Ariel,Renan Vieira Costa,5,Ariel
1,Ariel,Beatriz Diniz,5,Carolzinha
2,Ariel,Elio Ribeiro de Morais Filho,5,Davi
3,Ariel,thalita tayana dantas de sousa,5,Davi
4,Ariel,Maria Clara Gomes de Lacerda Quintans e Magalhães,5,Gelielison
...,...,...,...,...
214,Rodrigo,Leticia Costa,3,Rodrigo
215,Rodrigo,Maria Fernanda Burity,5,Rodrigo
216,Rodrigo,Rita de Cassia Cunha,5,Rodrigo
217,Rodrigo,Rodrigo Moura,2,Rodrigo
218,Rodrigo,Vitória Beatriz,3,Rodrigo

In [237]:
resulting.sort_values(by = "Assessor", inplace=True)

In [239]:
resulting.to_csv("final_allocation.csv", header=False, index = False)